-- Autorem tych prac jest: Zabójca997 SteamID: STEAM_0:0:96053498
-- © Prawa autorskie zastrzeżone.
-- Zakazuje usuwania linijki o autorze.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
TEAM_CITIZEN = DarkRP.createJob("Citizen", {
    color = Color(255, 120, 0, 255),
    model = {
        "models/classd/player/prisoners/jumpsuitm01.mdl",
        "models/classd/player/prisoners/jumpsuitm02.mdl",
        "models/classd/player/prisoners/jumpsuitm03.mdl",
        "models/classd/player/prisoners/jumpsuitm04.mdl",
        "models/classd/player/prisoners/jumpsuitm05.mdl",
        "models/classd/player/prisoners/jumpsuitm06.mdl",
		"models/classd/player/prisoners/jumpsuitm07.mdl",
    },
    description = [[Klasa D jest to domyślna klasa która jest brana na Badania]],
    weapons = {},
    command = "citizen",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Citizens",
	customCheck = function(ply) return
        table.HasValue({"STEAM_0:0:96053498"}, ply:SteamID())
    end,
})

TEAM_KLASAD = DarkRP.createJob("Klasa D", {
    color = Color(255, 120, 0, 255),
    model = {
        "models/classd/player/prisoners/jumpsuitm01.mdl",
        "models/classd/player/prisoners/jumpsuitm02.mdl",
        "models/classd/player/prisoners/jumpsuitm03.mdl",
        "models/classd/player/prisoners/jumpsuitm04.mdl",
        "models/classd/player/prisoners/jumpsuitm05.mdl",
        "models/classd/player/prisoners/jumpsuitm06.mdl",
		"models/classd/player/prisoners/jumpsuitm07.mdl",
    },
    description = [[Klasa D jest to domyślna klasa która jest brana na Badania]],
    weapons = {"weapon_fists", "weapon_empty_hands"},
    command = "KlasaD",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Klasy",
})

TEAM_KLASADZB = DarkRP.createJob("Klasa D - (Płatny zabójca)", {
    color = Color(255, 120, 0, 255),
    model = {
        "models/classd/player/prisoners/jumpsuitm01.mdl",
        "models/classd/player/prisoners/jumpsuitm02.mdl",
        "models/classd/player/prisoners/jumpsuitm03.mdl",
        "models/classd/player/prisoners/jumpsuitm04.mdl",
        "models/classd/player/prisoners/jumpsuitm05.mdl",
        "models/classd/player/prisoners/jumpsuitm06.mdl",
		"models/classd/player/prisoners/jumpsuitm07.mdl",
    },
    description = [[Klasa D jest to domyślna klasa z możliwością przyjęcia zabójstwa]],
    weapons = {"weapon_fists", "weapon_empty_hands"},
    command = "Klasaplatna",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Klasy",
})

TEAM_KLASAS = DarkRP.createJob("Sprzątacz", {
    color = Color(255, 120, 0, 255),
    model = {
        "models/player/kerry/class_jan_2.mdl",
        "models/player/kerry/class_jan_3.mdl",
        "models/player/kerry/class_jan_4.mdl",
        "models/player/kerry/class_jan_5.mdl",
        "models/player/kerry/class_jan_6.mdl",
        "models/player/kerry/class_jan_7.mdl",
    },
    description = [[Sprzątacze to klasa D uprawniona do czyszczenia fundacji za bycie grzecznym oraz podporządkowanym]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_pass_rp", "guthscp_keycard_lvl_1"},
    command = "Sprzatacz",
    max = 5,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 3,
    category = "Klasy",
})

TEAM_KWATER = DarkRP.createJob("Kwatermistrz", {
    color = Color(153, 79, 0, 255),
    model = {
        "models/player/portal/male_09_dode.mdl",
    },
    description = [[Sprzątacze to klasa D uprawniona do czyszczenia fundacji za bycie grzecznym oraz podporządkowanym]],
    weapons = {"weapon_fists", "weapon_empty_hands", "guthscp_keycard_lvl_1", "weapon_pass_rp"},
    command = "Kwatermistrz",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	hobo = true,
	level = 5,
    category = "Klasy",
})

TEAM_KUCHARZ = DarkRP.createJob("Kucharz", {
    color = Color(153, 79, 0, 255),
    model = {
        "models/player/p_butcher.mdl",
    },
    description = [[Kucharz to klasa D uprawniona do gotowania klasie D za bycie grzecznym oraz podporządkowanym]],
    weapons = {"weapon_fists", "weapon_empty_hands", "guthscp_keycard_lvl_1", "csgo_stiletto", "weapon_pass_rp"},
    command = "Kucharz",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	hobo = true,
	level = 6,
    category = "Klasy",
})

TEAM_POLICE = DarkRP.createJob("Civil Protection", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/police.mdl", "models/player/police_fem.mdl"},
    description = [[.]],
    weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
    command = "cp",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Civil Protection",
	customCheck = function(ply) return
        table.HasValue({"STEAM_0:0:96053498"}, ply:SteamID())
    end,
})

--TEAM_GANG = DarkRP.createJob("Gangster", {
--    color = Color(75, 75, 75, 255),
--    model = {
--        "models/player/Group03/Female_01.mdl",
--	},
--    description = [[]],
--    weapons = {},
--    command = "gangster",
--    max = 3,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    category = "Gangsters",
--})

TEAM_MOB = DarkRP.createJob("Mob boss", {
    color = Color(25, 25, 25, 255),
    model = "models/player/gman_high.mdl",
    description = [[The Mob boss is the boss of the criminals in the city.
        With his power he coordinates the gangsters and forms an efficient crime organization.
        He has the ability to break into houses by using a lockpick.
        The Mob boss posesses the ability to unarrest you.]],
    weapons = {"lockpick", "unarrest_stick"},
    command = "mobboss",
    max = 1,
    salary = GAMEMODE.Config.normalsalary * 1.34,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Gangsters",
	customCheck = function(ply) return
        table.HasValue({}, ply:SteamID())
    end,
})

--TEAM_GUN = DarkRP.createJob("Gun Dealer", {
--    color = Color(255, 140, 0, 255),
--    model = "models/player/monk.mdl",
--    description = [[A Gun Dealer is the only person who can sell guns to other people.
--        Make sure you aren't caught selling illegal firearms to the public! You might get arrested!]],
--    weapons = {},
--    command = "gundealer",
--    max = 2,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    category = "Citizens",
--})

--TEAM_MEDIC = DarkRP.createJob("Medic", {
--    color = Color(47, 79, 79, 255),
--    model = "models/player/kleiner.mdl",
--    description = [[With your medical knowledge you work to restore players to full health.
--        Without a medic, people cannot be healed.
--        Left click with the Medical Kit to heal other players.
--        Right click with the Medical Kit to heal yourself.]],
--    weapons = {"med_kit"},
--    command = "medic",
--    max = 3,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    medic = true,
--    category = "Citizens",
--})

--TEAM_CHIEF = DarkRP.createJob("Civil Protection Chief", {
--    color = Color(20, 20, 255, 255),
--    model = "models/player/combine_soldier_prisonguard.mdl",
--    description = [[The Chief is the leader of the Civil Protection unit.
--        Coordinate the police force to enforce law in the city.
--        Hit a player with arrest baton to put them in jail.
--        Bash a player with a stunstick and they may learn to obey the law.
--        The Battering Ram can break down the door of a criminal, with a warrant for his/her arrest.
--        Type /wanted <name> to alert the public to the presence of a criminal.
--        Type /jailpos to set the Jail Position]],
--    weapons = {"arrest_stick", "unarrest_stick", "weapon_deagle2", "stunstick", "door_ram", "weaponchecker"},
--    command = "chief",
--    max = 1,
--    salary = GAMEMODE.Config.normalsalary * 1.67,
--    admin = 0,
--    vote = false,
--    hasLicense = true,
--    chief = true,
--    NeedToChangeFrom = TEAM_POLICE,
--    ammo = {
--        ["pistol"] = 60,
--    },
--    category = "Civil Protection",
--})

--TEAM_MAYOR = DarkRP.createJob("Mayor", {
--    color = Color(150, 20, 20, 255),
--    model = "models/player/breen.mdl",
--    description = [[The Mayor of the city creates laws to govern the city.
--    If you are the mayor you may create and accept warrants.
--    Type /wanted <name>  to warrant a player.
--    Type /jailpos to set the Jail Position.
--    Type /lockdown initiate a lockdown of the city.
--    Everyone must be inside during a lockdown.
--    The cops patrol the area.
--    /unlockdown to end a lockdown]],
--    weapons = {},
--    command = "mayor",
--    max = 1,
--    salary = GAMEMODE.Config.normalsalary * 1.89,
--    admin = 0,
--    vote = true,
--    hasLicense = false,
--    mayor = true,
--    category = "Civil Protection",
--})

--TEAM_HOBO = DarkRP.createJob("Hobo", {
--    color = Color(80, 45, 0, 255),
--    model = "models/player/corpse1.mdl",
--    description = [[The lowest member of society. Everybody laughs at you.
--        You have no home.
--        Beg for your food and money
--        Sing for everyone who passes to get money
--        Make your own wooden home somewhere in a corner or outside someone else's door]],
--    weapons = {"weapon_bugbait"},
--    command = "hobo",
--    max = 5,
--    salary = 0,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    candemote = false,
--    hobo = true,
--    category = "Citizens",
--}) 

TEAM_ADMIN = DarkRP.createJob("Administracja", {
    color = Color(255, 0, 0, 250),
	model = {
        "models/player/inv2.mdl",
        "models/kss/tsremastered/smod_tactical_soldier.mdl",
    },
    description = [[Jest to Administracja serwer obecna do pomocy inaczej AdminOnDuty]],
    weapons = {"arrest_stick", "door_ram", "lockpick", "stunstick", "pocketchecker", "hidden_knife", "weapon_camo", "weapon_beam", "card_lvl_5", "wep_jack_job_drpstungun"},
    command = "Admini",
    max = 2,
    salary = 1000,
    admin = 2,
    vote = false,
    hasLicense = true,
    candemote = true,
	mayor = true,
    category = "Admin of duty",
})
-- SCP
TEAM_SCP173 = DarkRP.createJob("SCP 173", {
    color = Color(150, 63, 0),
    model = "models/cpthazama/scp/173.mdl",
    description = [[SCP-173 jest zbudowany z betonu i prętów zbrojeniowych oraz pomalowany farbą. SCP-173 jest żywy i ekstremalnie niebezpieczny. Obiekt nie może się poruszać, kiedy ktokolwiek na niego patrzy. Z obiektem należy zawsze utrzymywać kontakt wzrokowy.]],
    weapons = {"weapon_scp173"},
    command = "SCP-173",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 10,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(0)
    end
})

TEAM_SCP106 = DarkRP.createJob("SCP 106 [WL]", {
    color = Color(150, 63, 0),
    model = "models/cpthazama/scpunity/106.mdl",
    description = [[SCP-106 to osobnik potrafiący przenieść cie do świata łzowego, może on przechodzić przez drzwi]],
    weapons = {"gu_scp_106", "guthscp_keycard_lvl_4"},
    command = "SCP-106",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 15,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(0)
    end
})

TEAM_SCP096 = DarkRP.createJob("SCP 096", {
    color = Color(150, 63, 0),
    model = "models/scp096anim/player/scp096pm_raf.mdl",
    description = [[SCP-096 Nieśmiałek nie wolno sie na niego patrzeć gdyż powoduje to u niego stan w którym bedzie musiał cie zabić!]],
    weapons = {"weapon_scp096swep"},
    command = "SCP-096",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 11,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(0)
    end
})

TEAM_SCP999 = DarkRP.createJob("SCP 999", {
    color = Color(150, 63, 0),
    model = "models/scp/999/jq/scp_999_pmjq.mdl",
    description = [[SCP-999 Jest to glut którego zdolności mogą wyleczyć cie z depresji lub uleczyć cie]],
    weapons = {"med_kit", "cscp_999"},
    command = "SCP-999",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 5,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(3000)
        ply:SetHealth(3000)
        ply:SetArmor(0)
    end
})

TEAM_SCP066 = DarkRP.createJob("SCP 066", {
    color = Color(150, 63, 0),
    model = "models/cpthazama/scp/066.mdl",
    description = [[SCP-066 To zabawka ericka która gdy nie potwierdzisz że jesteś erickiem może wydać z siebie mocny dzwięk zabijając cie]],
    weapons = {"weapon_scp066"},
    command = "SCP-066",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 7,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(3000)
        ply:SetHealth(3000)
        ply:SetArmor(0)
    end
})

TEAM_SCP131 = DarkRP.createJob("SCP 131", {
    color = Color(150, 63, 0),
    model = "models/thenextscp/scp131/scp131.mdl",
    description = [[SCP-131 Oczki strączne]],
    weapons = {"weapon_empty_hands"},
    command = "scp-131",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 6,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(2000)
        ply:SetHealth(2000)
        ply:SetArmor(0)
    end
})

TEAM_SCP1991 = DarkRP.createJob("SCP 1991 [VIP]", {
    color = Color(150, 63, 0),
    model = "models/siren_head_player_jq1991.mdl",
    description = [[SCP-1991 SirenHead jest to potwór który może zabić cie gdy jesteś przy nim]],
    weapons = {"siren_head_swep"},
    command = "SCP-1991",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 15,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(0)
    end
})

TEAM_SCP023 = DarkRP.createJob("SCP 023 [VIP]", {
    color = Color(150, 63, 0),
    model = "models/novux/023/novux_scp-023.mdl",
    description = [[SCP-023 Cień wilka]],
    weapons = {"weapon_pet", "weapon_empty_hands"},
    command = "SCP-023",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 8,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP939 = DarkRP.createJob("SCP 939", {
    color = Color(150, 63, 0),
	model = "models/scp/939/unity/unity_scp_939.mdl",
    description = [[SCP-939 Jaszczur! nie widzi lecz bardzo dobrze słyszy a przy tym wypuszcza gaz amnezyjny]],
    weapons = {"weapon_scp939swep"},
    command = "SCP-939",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 10,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(8000)
        ply:SetHealth(8000)
        ply:SetArmor(0)
    end
})

TEAM_SCP1048A = DarkRP.createJob("SCP 1048-A", {
    color = Color(150, 63, 0),
	model = "models/1048/tdy/tdybrownpm.mdl",
    description = [[SCP-1048 Miś budowlany]],
    weapons = {"weapon_empty_hands"},
    command = "SCP-1048A",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 3,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(2000)
        ply:SetHealth(2000)
        ply:SetArmor(0)
    end
})

TEAM_SCP1048B = DarkRP.createJob("SCP 1048-B", {
    color = Color(150, 63, 0),
	model = "models/cpthazama/scp/1048a.mdl",
    description = [[SCP-1048 Miś z uszu]],
    weapons = {"csgo_stiletto"},
    command = "SCP-1048B",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 8,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP682 = DarkRP.createJob("SCP 682 [WL]", {
    color = Color(150, 63, 0),
    model = "models/cultist_kun/scp_crock_v2.mdl",
    description = [[SCP-682 Nie nawidzi życia! zabija wszystko co sie rusza]],
    weapons = {"weapon_scp682"},
    command = "SCP-682",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 20,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(50000)
        ply:SetHealth(50000)
        ply:SetArmor(0)
    end
})

TEAM_SCP049 = DarkRP.createJob("SCP 049", {
    color = Color(150, 63, 0),
    model = "models/vinrax/player/scp049_player.mdl",
    description = [[SCP-049 Plaga! Zabija dotykiem zamieniając cie w zombie]],
    weapons = {"scp_049_scp"},
    command = "SCP-049",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 10,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(100)
    end
})

TEAM_SCP966 = DarkRP.createJob("SCP 966", {
    color = Color(150, 63, 0),
    model = "models/cpthazama/scp/966.mdl",
    description = [[SCP-966 Niewidzialny! widzisz go tylko w NVG może cie próbować uspać]],
    weapons = {"weapon_966"},
    command = "SCP-966",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 8,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP457 = DarkRP.createJob("SCP 457", {
    color = Color(150, 63, 0),
    model = "models/player/undead/undead.mdl",
    description = [[SCP-457 jest to palący sie humanoid]],
    weapons = {"weapon_scp457"},
    command = "SCP-457",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 9,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP076 = DarkRP.createJob("SCP 076", {
    color = Color(150, 63, 0),
    model = "models/abel/abel.mdl",
    description = [[SCP-076 Abel jest humanoidem]],
    weapons = {"weapon_katana"},
    command = "SCP-076",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 7,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(8000)
        ply:SetHealth(8000)
        ply:SetArmor(0)
    end
})

TEAM_SCP343 = DarkRP.createJob("SCP 343", {
    color = Color(150, 63, 0),
    model = "models/player/gow3_zeus.mdl",
    description = [[SCP-343 Zwany bogiem]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_medkit"},
    command = "SCP-343",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 13,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})
-- MFO Hammer Down
TEAM_MFOHDZ = DarkRP.createJob("Zołnierz MFO - Hammer Down [WL]", {
    color = Color(0, 22, 150),
    model = {
        "models/npc/portal/male_02_garde.mdl",
        "models/npc/portal/male_04_garde.mdl",
        "models/npc/portal/male_05_garde.mdl",
        "models/npc/portal/male_06_garde.mdl",
    },
    description = [[Żołnierz MFO Hammer-Down jest batalionem składającym się z trzech wyspecjalizowanych pułków piechoty wielkości kompanii]],
    weapons = {"cw_ar15", "sg_adrenaline", "cw_p99", "csgo_m9_night", "cw_flash_grenade", "guthscp_keycard_lvl_3", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "MFO-Hammer-Down",
    max = 5,
    salary = 30,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(130)
    end
})

TEAM_MFOHDGEN = DarkRP.createJob("General MFO - Hammer Down [WL]", {
    color = Color(0, 22, 150),
	model = {
        "models/npc/portal/male_08_garde.mdl",
    },
    description = [[Generał Mobilnej formacji operacyjnej]],
    weapons = {"cw_deagle", "sg_adrenaline", "cw_kk_hk416", "weapon_empty_hands", "weapon_pass_rp", "csgo_karambit_marblefade", "cw_flash_grenade", "keys", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "MFO-General",
    max = 1,
    salary = 30,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(150)
    end
})

TEAM_MFOHDMED = DarkRP.createJob("Medyk MFO - Hammer Down [WL]", {
    color = Color(0, 22, 150),
    model = {
        "models/payday2/units/medic_player.mdl",
        "models/payday2/units/medic_player_pd2anim.mdl",
    },
    description = [[Medyk Mobilnej formacji operacyjnej ma za zadanie leczyć swoich]],
    weapons = {"med_kit", "sg_adrenaline", "cw_ws_kabar", "cw_p99", "keys", "cw_flash_grenade", "weapon_empty_hands", "weapon_pass_rp", "weapon_cuff_elastic", "guthscp_keycard_lvl_3", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "MFOHD-medyk",
    max = 2,
    salary = 40,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 10,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_MFOHDDOG = DarkRP.createJob("Pies MFO - Hammer Down [WL]", {
    color = Color(0, 22, 150),
    model = "models/arachnit/wolfenstein2/kampfhund/kampfhund.mdl",
    description = [[Pies Mobilnej formacji operacyjnej ma za zadanie Pilnować porządku i wyszukiwać kontrabande]],
    weapons = {"weapon_pet", "weapon_empty_hands", "weapon_empty_hands"},
    command = "MFOHD-pies",
    max = 1,
    salary = 40,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})
-- Wsparcie fundacji
TEAM_MFOW = DarkRP.createJob("[EVENTOWY] Wsparcie Fundacji Klasy D [VIP]", {
    color = Color(0, 37, 250),
    model = {
        "models/konnie/isa/detroit/swat_soldier.mdl",
        "models/konnie/isa/detroit/swat_soldier_2.mdl",
        "models/konnie/isa/detroit/swat_captainallen.mdl",
    },
    description = [[Jest to Wsparcie Mobilnej formacji operacyjnej do zamieszek Klasy D]],
    weapons = {"cw_blackops3_dlc2_isr27", "sg_adrenaline", "cw_blackops3_mr6", "cw_blackops3_melee_combat", "cw_flash_grenade", "weapon_empty_hands", "keys", "weapon_pass_rp", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "weapon_camo", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "MFO-Wsparcie-Klasy-D",
    max = 5,
    salary = 40,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Eventowe",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(200)
    end
})

TEAM_MFOWS = DarkRP.createJob("[EVENTOWY] Wsparcie Fundacji SCP [VIP]", {
    color = Color(0, 37, 250),
    model = {
		"models/konnie/isa/detroit/swat_soldier.mdl",
		"models/konnie/isa/detroit/swat_soldier_2.mdl",
		"models/konnie/isa/detroit/swat_captainallen.mdl",
    },
    description = [[Jest to Wsparcie Mobilnej formacji operacyjnej do zamieszek SCP]],
    weapons = {"cw_blackops3_dlc2_isr27", "sg_adrenaline", "cw_blackops3_mr6", "cw_blackops3_melee_combat", "cw_flash_grenade", "weapon_empty_hands", "keys", "weapon_pass_rp", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "weapon_camo", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "MFO-Wsparcie-SCP",
    max = 5,
    salary = 40,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Eventowe",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(200)
    end
})
-- CI
TEAM_CIR = DarkRP.createJob("[EVENTOWY] Zołnierz CI", {
    color = Color(1, 148, 58),
    model = "models/friskiukas/bf4/ru_01.mdl",
    description = [[Rekrut rebeli chaosu]],
    weapons = {"cw_ak74", "sg_adrenaline", "cw_smoke_grenade", "cw_flash_grenade", "cw_m1911", "csgo_bayonet_rustcoat", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "weapon_hdevice"},
    command = "CI-Rekrut",
    max = 0,
    salary = 30,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Rebelia Chaosu",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_CIS = DarkRP.createJob("[EVENTOWY] Zwiadowca CI", {
    color = Color(1, 148, 58),
    model = {
        "models/player/pmc_4/pmc__02.mdl",
        "models/player/pmc_4/pmc__03.mdl",
        "models/player/pmc_4/pmc__04.mdl",
        "models/player/pmc_4/pmc__05.mdl",
        "models/player/pmc_4/pmc__06.mdl",
        "models/player/pmc_4/pmc__07.mdl",
        "models/player/pmc_4/pmc__08.mdl",
		"models/player/pmc_4/pmc__09.mdl",
		"models/player/pmc_4/pmc__10.mdl",
		"models/player/pmc_4/pmc__11.mdl",
		"models/player/pmc_4/pmc__12.mdl",
		"models/player/pmc_4/pmc__13.mdl",
		"models/player/pmc_4/pmc__14.mdl",
    },
    description = [[Zwiadowca rebeli chaosu]],
    weapons = {"cw_l85a2", "sg_adrenaline", "cw_smoke_grenade", "cw_flash_grenade", "cw_m1911", "csgo_bayonet_rustcoat", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "weapon_hdevice"},
    command = "CI-Szeregowy",
    max = 6,
    salary = 30,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Rebelia Chaosu",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(0)
    end
})

TEAM_CIG = DarkRP.createJob("[EVENTOWY] Generał CI [WL]", {
    color = Color(1, 148, 58),
    model = "models/player/pmc_1/pmc__01.mdl",
    description = [[Generał rebeli chaosu]],
    weapons = {"cw_m14", "sg_adrenaline", "cw_smoke_grenade", "cw_flash_grenade", "cw_m1911", "csgo_butterfly_crimsonwebs", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "weapon_hdevice", "wep_jack_job_drpradio"},
    command = "CI-Generał",
    max = 1,
    salary = 30,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Rebelia Chaosu",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})
-- Zarząd
TEAM_DEPZARZ = DarkRP.createJob("Rada O5 [Admin Only]", {
    color = Color(66, 66, 66),
    model = {
        "models/player/nick/scp/head_of_security/hos.mdl",
		"models/player/nick/scp/site_director/sd.mdl",
		"models/player/suits/male_09_open_waistcoat.mdl",
		"models/player/suits/male_09_open_tie.mdl",
		"models/player/suits/male_09_open.mdl",
		"models/player/suits/male_09_closed_tie.mdl",
		"models/player/suits/male_09_closed_coat_tie.mdl",
		"models/player/suits/male_08_shirt_tie.mdl",
		"models/player/suits/male_08_shirt.mdl",
		"models/player/suits/male_08_open_waistcoat.mdl",
		"models/player/suits/male_08_open_tie.mdl",
		"models/player/suits/male_08_open.mdl",
		"models/player/suits/male_08_closed_tie.mdl",
		"models/player/suits/male_08_closed_coat_tie.mdl",
		"models/player/suits/male_07_shirt_tie.mdl",
		"models/player/suits/male_07_shirt.mdl",
		"models/player/suits/male_07_open_waistcoat.mdl",
		"models/player/suits/male_07_open_tie.mdl",
		"models/player/suits/male_07_open.mdl",
		"models/player/suits/male_07_closed_tie.mdl",
		"models/player/suits/male_07_closed_coat_tie.mdl",
		"models/player/suits/male_06_shirt_tie.mdl",
		"models/player/suits/male_06_shirt.mdl",
		"models/player/suits/male_06_open_waistcoat.mdl",
		"models/player/suits/male_06_open_tie.mdl",
		"models/player/suits/male_06_open.mdl",
		"models/player/suits/male_06_closed_tie.mdl",
		"models/player/suits/male_06_closed_coat_tie.mdl",
		"models/player/suits/male_05_shirt_tie.mdl",
		"models/player/suits/male_05_open_waistcoat.mdl",
		"models/player/suits/male_05_open_tie.mdl",
		"models/player/suits/male_05_open.mdl",
		"models/player/suits/male_05_closed_tie.mdl",
		"models/player/suits/male_04_shirt_tie.mdl",
		"models/player/suits/male_04_shirt.mdl",
		"models/player/suits/male_04_open_waistcoat.mdl",
		"models/player/suits/male_04_open_tie.mdl",
		"models/player/suits/male_04_open.mdl",
		"models/player/suits/male_04_closed_tie.mdl",
		"models/player/suits/male_04_closed_coat_tie.mdl",
		"models/player/suits/male_03_shirt_tie.mdl",
		"models/player/suits/male_03_shirt.mdl",
		"models/player/suits/male_03_open_waistcoat.mdl",
		"models/player/suits/male_03_open_tie.mdl",
		"models/player/suits/male_03_open.mdl",
		"models/player/suits/male_03_closed_tie.mdl",
	},
    description = [[Dowództwo O5. Jest tajny i zwracać można sie do nich wyższy komitecie ds. etyki]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_fiveseven", "door_ram", "weapon_stunstick", "sg_medkit", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "guthscp_keycard_lvl_5", "wep_jack_job_drpradio"},
    command = "radao5",
    max = 5,
    salary = 300,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Zarząd",
	mayor = true,
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(3000)
        ply:SetHealth(3000)
        ply:SetArmor(100)
    end
})

TEAM_DEPDYR = DarkRP.createJob("Dyrektor Placówki [WL]", {
    color = Color(66, 66, 66),
    model = {
        "models/player/nick/scp/head_of_security/hos.mdl",
		"models/player/nick/scp/site_director/sd.mdl",
		"models/player/suits/male_05_open_tie.mdl",
		"models/player/suits/male_05_open.mdl",
		"models/player/suits/male_05_closed_tie.mdl",
	},
    description = [[Dyrektorzy istotnych placówek Fundacji to najważniejsi ich pracownicy odpowiedzialni za wszystko.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_fiveseven", "weapon_stunstick", "door_ram", "sg_medkit", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "wep_jack_job_drpradio"},
    command = "Dyrektorp",
    max = 1,
    salary = 290,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Zarząd",
	mayor = true,
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(2000)
        ply:SetHealth(2000)
        ply:SetArmor(50)
    end
})
-- VIP
TEAM_DEPDS = DarkRP.createJob("Specjalista ds. przechowywania [VIP]", {
    color = Color(110, 110, 110),
    model = "models/cultist/scp_rp/scientists_6.mdl",
    description = [[Pełnisz role w zespołach zabezpieczających do potwierdzonych anomalii, by je zabezpieczyć ]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_3", "weapon_cuff_elastic"},
    command = "spedsp",
    max = 1,
    salary = 150,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 9,
    category = "Zarząd",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(50)
    end
})

TEAM_DEPDS = DarkRP.createJob("Likwidator biologiczny [VIP]", {
    color = Color(2, 14, 153),
    model = {
        "models/player/tfa_trent_cleaner_grenadier.mdl",
        "models/player/tfa_trent_cleaner_mech.mdl",
        "models/player/ztfa_trent_cleaner_grenadier.mdl",
        "models/player/ztfa_trent_cleaner_mech.mdl",
    },
    description = [[Ma za zadanie zwalczyć biologiczne choroby, Przedmioty czy anomalie.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_3", "weapon_ai_flamethrower"},
    command = "likwidator",
    max = 6,
    salary = 140,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Departament",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(80)
    end
})
-- Departamenty
TEAM_DEPLOG = DarkRP.createJob("Logistyki", {
    color = Color(153, 2, 75),
    model = {
        "models/cultist/worker_f.mdl",
        "models/cultist/worker_f2.mdl",
        "models/cultist/worker_f3.mdl",
        "models/cultist/worker_f4.mdl",
        "models/cultist/worker_f5.mdl",
        "models/cultist/worker_male.mdl",
		"models/cultist/worker_male2.mdl",
		"models/cultist/worker_male3.mdl",
		"models/cultist/worker_male4.mdl",
		"models/cultist/worker_male5.mdl",
    },
    description = [[DL odpowiedzialny jest za transfery zasobów naturalnych, finansowych oraz ludzkich pomiędzy placówkami.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_2"},
    command = "Dep-log",
    max = 5,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 1,
    category = "Departament",
})

TEAM_DEPMED = DarkRP.createJob("Medycyny", {
    color = Color(153, 2, 75),
    model = {
        "models/player/kerry/medic/medic_01.mdl",
        "models/player/kerry/medic/medic_01_f.mdl",
        "models/player/kerry/medic/medic_02.mdl",
        "models/player/kerry/medic/medic_02_f.mdl",
        "models/player/kerry/medic/medic_03.mdl",
        "models/player/kerry/medic/medic_03_f.mdl",
		"models/player/kerry/medic/medic_04.mdl",
		"models/player/kerry/medic/medic_04_f.mdl",
		"models/player/kerry/medic/medic_05.mdl",
		"models/player/kerry/medic/medic_05_f.mdl",
		"models/player/kerry/medic/medic_06.mdl",
		"models/player/kerry/medic/medic_06_f.mdl",
		"models/player/kerry/medic/medic_07.mdl",
    },
    description = [[DM odpowiedzialny jest za utrzymywanie zdrowia pracowników SCP.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_2", "med_kit"},
    command = "Dep-Med",
    max = 5,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 3,
    category = "Departament",
})
-- Komitet
TEAM_DEPET = DarkRP.createJob("Komitet ds. Etyki [WL]", {
    color = Color(153, 2, 75),
    model = {
		"models/player/suits/male_03_shirt_tie.mdl",
		"models/player/suits/male_03_shirt.mdl",
		"models/player/suits/male_03_open_waistcoat.mdl",
		"models/player/suits/male_03_open_tie.mdl",
		"models/player/suits/male_03_open.mdl",
		"models/player/suits/male_03_closed_tie.mdl",
    },
    description = [[Możesz mówić że coś jest nie etyczne oraz przerywać i karać osoby które robią coś nie etycznego.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_4", "med_kit", "weapon_cuff_elastic", "wep_jack_job_drpradio"},
    command = "Dep-Etyk",
    max = 1,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Zarząd",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(90)
    end
})

TEAM_DEPINZ = DarkRP.createJob("Inżynierii", {
    color = Color(153, 2, 75),
    model = "models/humans/bms_engineer.mdl",
    description = [[DI odpowiedzialny jest za utrzymywanie sprzętu technicznego oraz wszelkich usług dostępnych w placówkach Fundacji ]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_3"},
    command = "Dep-Inz",
    max = 5,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 2,
    category = "Departament",
})

TEAM_SZEFOCH = DarkRP.createJob("Szef Ochrony [WL]", {
	color = Color(1, 84, 153, 255),
	model = {
        "models/player/suits/male_01_closed_coat_tie.mdl",
        "models/player/suits/male_01_closed_tie.mdl",
        "models/player/suits/male_01_open.mdl",
        "models/player/suits/male_01_open_tie.mdl",
        "models/player/suits/male_01_open_waistcoat.mdl",
        "models/player/suits/male_01_shirt_tie.mdl",
        "models/player/suits/male_01_shirt.mdl",
		"models/player/suits/male_02_closed_coat_tie.mdl",
		"models/player/suits/male_02_closed_tie.mdl",
    },
	description = [[Szef ochrony zarządza całym FO]],
	weapons = {"cw_mp5", "sg_adrenaline", "cw_fiveseven", "guthscp_keycard_lvl_3", "weapon_empty_hands", "stunstick", "pocket", "salute_swep", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "cross_arms_infront_swep", "wep_jack_job_drpradio"},
	command = "SzefOch",
	max = 4,
	salary = 100,
	admin = 0,
	vote = false,
	hasLicense = true,
	candemote = true,
	category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_AgentDB = DarkRP.createJob("Agent DB [WL]", {
	color = Color(1, 84, 153, 255),
	model = {
        "models/player/suits/male_01_closed_coat_tie.mdl",
        "models/player/suits/male_01_closed_tie.mdl",
        "models/player/suits/male_01_open.mdl",
        "models/player/suits/male_01_open_tie.mdl",
        "models/player/suits/male_01_open_waistcoat.mdl",
        "models/player/suits/male_01_shirt_tie.mdl",
        "models/player/suits/male_01_shirt.mdl",
		"models/player/suits/male_02_closed_coat_tie.mdl",
		"models/player/suits/male_02_closed_tie.mdl",
    },
	description = [[Departament bezpieczeństwa zarządza całym bezpieczeństwem w placówce]],
	weapons = {"cw_mp5", "sg_adrenaline", "cw_fiveseven", "guthscp_keycard_lvl_4", "weapon_empty_hands", "stunstick", "pocket", "salute_swep", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "cross_arms_swep", "cross_arms_infront_swep", "wep_jack_job_drpradio"},
	command = "Agentdb",
	max = 1,
	salary = 100,
	admin = 0,
	vote = false,
	hasLicense = true,
	candemote = true,
	category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})
-- FO
TEAM_OCHRONASA = DarkRP.createJob("FO - Sanitariusz Ochrona [WL]", {
    color = Color(2, 90, 153),
    model = {
        "models/payday2/units/medic_player_pd2anim.mdl",
    },
    description = [[Sanitariusz ochrony zajmuje sie pilnowaniem Klasy D oraz badaniami na SCP lecz swoich kolegów z fo]],
    weapons = {"weapon_fists", "weapon_empty_hands", "csgo_m9_night", "weapon_stunstick", "cw_fiveseven", "cw_g36c", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_2", "salute_swep", "wep_jack_job_drpradio"},
    command = "Ochrona-SA",
    max = 2,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 3,
    category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(50)
    end
})

TEAM_OCHRONA = DarkRP.createJob("FO - Ochrona [WL]", {
    color = Color(2, 90, 153),
    model = {
        "models/scprp/riot_06.mdl",
        "models/scprp/riot_07.mdl",
        "models/scprp/riot_08.mdl",
		"models/scprp/riot_09.mdl",
    },
    description = [[Ochrona główna zajmuje sie pilnowaniem Klasy D pilnowaniem nad bezpieczeństwem i przed wyłomami oraz eskorta SCP]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "weapon_stunstick", "cw_fiveseven", "cw_ump45", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_2", "salute_swep", "wep_jack_job_drpradio"},
    command = "Ochrona-G",
    max = 5,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(50)
    end
})

TEAM_POCHRONA = DarkRP.createJob("FO - Rekrut", {
    color = Color(2, 90, 153),
    model = {
        "models/scprp/riot_01.mdl",
        "models/scprp/riot_02.mdl",
        "models/scprp/riot_03.mdl",
        "models/scprp/riot_05.mdl",
    },
    description = [[Rekrut ochrony zajmuje sie pilnowaniem Klasy D]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "weapon_stunstick", "cw_fiveseven", "cw_kk_hk416", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_3", "salute_swep", "wep_jack_job_drpradio"},
    command = "Ochrona-por",
    max = 5,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 3,
    category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(60)
    end
})
-- MFO Alpha 1
TEAM_MFOA1GEN = DarkRP.createJob("Generał MFO - Alpha 1 [WL]", {
    color = Color(2, 90, 153),
    model = "models/kss/tsremastered/smod_operator_tac_01.mdl",
    description = [[Formacja odpowiadająca bezpośrednio przed Radą O5 oraz dyrektora placówki masz przy nich być i ich chronić oraz szkolić swoich]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_blackops3_dlc2_arak", "salute_swep", "csgo_falchion_crimsonwebs", "wep_jack_job_drpradio", "cw_blackops3_mr6", "cw_flash_grenade", "sg_adrenaline", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_4", "weapon_ai_noisemaker"},
    command = "MFOA1G",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Alpha 1",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_MFOA1 = DarkRP.createJob("MFO - Alpha 1 [WL]", {
    color = Color(2, 90, 153),
    model = {
        "models/scp_mtf_russian/mtf_rus_02.mdl",
        "models/scp_mtf_russian/mtf_rus_04.mdl",
        "models/scp_mtf_russian/mtf_rus_05.mdl",
		"models/scp_mtf_russian/mtf_rus_06.mdl",
		"models/scp_mtf_russian/mtf_rus_07.mdl",
		"models/scp_mtf_russian/mtf_rus_08.mdl",
    },
    description = [[Formacja odpowiadająca bezpośrednio przed Radą O5 oraz dyrektora placówki masz przy nich być i ich chronić]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_blackops3_dlc2_arak", "salute_swep", "csgo_falchion_bluesteel", "wep_jack_job_drpradio", "cw_blackops3_mr6", "cw_flash_grenade", "sg_adrenaline", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_4", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "MFOA1",
    max = 6,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Alpha 1",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})
-- Naukowcy
TEAM_ASNaukowiec = DarkRP.createJob("Asystent Naukowy", {
    color = Color(0, 149, 255),
    model = {
        "models/cultist/scp_rp/scientists_1.mdl",
        "models/cultist/scp_rp/scientists_2.mdl",
        "models/cultist/scp_rp/scientists_3.mdl",
        "models/cultist/scp_rp/scientists_4.mdl",
        "models/cultist/scp_rp/scientists_5.mdl",
        "models/cultist/scp_rp/scientists_6.mdl",
        "models/cultist/scp_rp/scientists_7.mdl",
		"models/cultist/scp_rp/scientists_8.mdl",
		"models/cultist/scp_rp/scientists_9.mdl",
    },
    description = [[Jako asystent ucz sie badań i możesz przeprowadzać badania nad klasą Safe i składać raporty głównemu naukowcowi.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_1", "wep_jack_job_drpradio"},
    command = "ASNaukowiec",
    max = 6,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 3,
    category = "Naukowcy",
})

TEAM_Naukowiec = DarkRP.createJob("Naukowiec", {
    color = Color(0, 149, 255),
    model = {
        "models/cultist/scp_rp/scientists_1.mdl",
        "models/cultist/scp_rp/scientists_2.mdl",
        "models/cultist/scp_rp/scientists_3.mdl",
        "models/cultist/scp_rp/scientists_4.mdl",
        "models/cultist/scp_rp/scientists_5.mdl",
        "models/cultist/scp_rp/scientists_6.mdl",
        "models/cultist/scp_rp/scientists_7.mdl",
		"models/cultist/scp_rp/scientists_8.mdl",
		"models/cultist/scp_rp/scientists_9.mdl",
    },
    description = [[Jako naukowiec możesz przeprowadzać badania nad Euclidami i składać raporty głównemu naukowcowi]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "weapon_stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_3", "wep_jack_job_drpradio"},
    command = "Naukowiec",
    max = 6,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 8,
    category = "Naukowcy",
})

TEAM_MŁNaukowiec = DarkRP.createJob("Młodszy Naukowiec", {
    color = Color(0, 149, 255),
    model = {
        "models/cultist/scp_rp/scientists_1.mdl",
        "models/cultist/scp_rp/scientists_2.mdl",
        "models/cultist/scp_rp/scientists_3.mdl",
        "models/cultist/scp_rp/scientists_4.mdl",
        "models/cultist/scp_rp/scientists_5.mdl",
        "models/cultist/scp_rp/scientists_6.mdl",
        "models/cultist/scp_rp/scientists_7.mdl",
		"models/cultist/scp_rp/scientists_8.mdl",
		"models/cultist/scp_rp/scientists_9.mdl",
    },
    description = [[Jako młodszy naukowiec możesz przeprowadzać badania nad Euclidami i składać raporty głównemu naukowcowi]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep","keys", "weapon_pass_rp", "guthscp_keycard_lvl_2", "weapon_stunstick", "wep_jack_job_drpradio"},
    command = "Mł-Naukowiec",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 5,
    category = "Naukowcy",
})

TEAM_STNaukowiec = DarkRP.createJob("Starszy Naukowiec", {
    color = Color(0, 149, 255),
    model = {
        "models/cultist/scp_rp/scientists_1.mdl",
        "models/cultist/scp_rp/scientists_2.mdl",
        "models/cultist/scp_rp/scientists_3.mdl",
        "models/cultist/scp_rp/scientists_4.mdl",
        "models/cultist/scp_rp/scientists_5.mdl",
        "models/cultist/scp_rp/scientists_6.mdl",
        "models/cultist/scp_rp/scientists_7.mdl",
		"models/cultist/scp_rp/scientists_8.mdl",
		"models/cultist/scp_rp/scientists_9.mdl",
    },
    description = [[Jako Starszy naukowiec masz za zadanie badać Klase Keter i składać o nich raporty Naukowcowi głównemu.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_3", "weapon_stunstick", "wep_jack_job_drpradio"},
    command = "ST-Naukowiec",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 10,
    category = "Naukowcy",
})

TEAM_GłNaukowiec = DarkRP.createJob("Główny Naukowiec [WL]", {
    color = Color(0, 149, 255),
    model = "models/cultist/scp_rp/scientists_1.mdl",
    description = [[Jako główny naukowiec możesz zatwierdzać badania oraz szkolic swoich naukowców i przydzielać im tytuły.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "weapon_stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_4", "wep_jack_job_drpradio"},
    command = "Gł-Naukowiec",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Naukowcy",
})
-- FT
TEAM_FTS = DarkRP.createJob("FT - Żołnierz [WL]", {
    color = Color(0, 149, 255),
    model = "models/player/kerry/1swat_ls.mdl",
    description = [[Zajmuj sie odparciem wroga oraz wyłamaniom SCP.]],
    weapons = {"cw_m14","cw_p99", "weapon_empty_hands", "weapon_cuff_elastic", "salute_swep", "weapon_stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_3", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "FT-Żołnierz",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "FT Siły Reagowania",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(90)
    end
})

TEAM_FTG = DarkRP.createJob("FT - Dowódca [WL]", {
    color = Color(0, 149, 255),
    model = "models/player/kerry/swat_ls.mdl",
    description = [[Szkol FT i zajmuj sie odparciem wroga oraz wyłamaniom SCP.]],
    weapons = {"cw_m14", "cw_fiveseven", "weapon_cuff_elastic", "weapon_empty_hands", "salute_swep", "weapon_stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_4", "cross_arms_swep", "cross_arms_infront_swep", "wep_jack_job_drpradio", "weapon_ai_noisemaker"},
    command = "FT-General",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "FT Siły Reagowania",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})
-- Inne
TEAM_CYW = DarkRP.createJob("Cywil [UCIECZKA]", {
    color = Color(0, 149, 255),
    model = {
        "models/cultist/worker_f.mdl",
        "models/cultist/worker_f2.mdl",
        "models/cultist/worker_f3.mdl",
        "models/cultist/worker_f4.mdl",
        "models/cultist/worker_f5.mdl",
        "models/cultist/worker_male.mdl",
        "models/cultist/worker_male2.mdl",
		"models/cultist/worker_male3.mdl",
		"models/cultist/worker_male4.mdl",
		"models/cultist/worker_male5.mdl",
    },
    description = [[Cywil osoba która uciekła z placówki.]],
    weapons = {"weapon_empty_hands", "weapon_fists", "weapon_pass_rp"},
    command = "cywil",
    max = 10,
    salary = 30,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Eventowe",
})

TEAM_JACK = DarkRP.createJob("Dr. Jack Bright [WL]", {
    color = Color(0, 149, 255),
    model = {
        "models/player/kerry/class_scientist_1.mdl",
    },
    description = [[Postać kanoniczna Dr. Jack Bright.]],
    weapons = {"weapon_empty_hands", "weapon_fists", "weapon_pass_rp", "sg_adrenaline", "guthscp_keycard_lvl_4", "wep_jack_job_drpradio"},
    command = "jb",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Naukowcy",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_AGENT = DarkRP.createJob("[EVENTOWY] Tajny Agent", {
    color = Color(0, 149, 255),
    model = {
        "models/player/fyk/smith1.mdl",
    },
    description = [[Jest to agent fundacji.]],
    weapons = {"weapon_empty_hands", "weapon_fists", "weapon_pass_rp", "sg_adrenaline", "cw_fiveseven", "wep_jack_job_drpradio"},
    command = "agent",
    max = 1,
    salary = 300,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 15,
    category = "Eventowe",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

if not DarkRP.disabledDefaults["modules"]["hungermod"] then
    TEAM_COOK = DarkRP.createJob("Cook", {
        color = Color(238, 99, 99, 255),
        model = "models/player/mossman.mdl",
        description = [[As a cook, it is your responsibility to feed the other members of your city.
            You can spawn a microwave and sell the food you make:
            /buymicrowave]],
        weapons = {},
        command = "cook",
        max = 2,
        salary = 45,
        admin = 0,
        vote = false,
        hasLicense = false,
        cook = true
    })
end

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Door groups
AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
AddDoorGroup("Gundealer only", TEAM_GUN)


-- Agendas
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})

-- Group chats
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_MFOA1GEN, TEAM_MFOA1)
DarkRP.createGroupChat(TEAM_MFOHDZW, TEAM_MFOR, TEAM_MFOMED, TEAM_MFODOG, TEAM_MFOW, TEAM_MFOWS, TEAM_MFOHDGEN)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_KLASAD

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,
	[TEAM_ADMIN] = true,
	[TEAM_MFOA1GEN] = true,
	[TEAM_MFOA1] = true,
	[TEAM_MFOHDZW] = true,
	[TEAM_MFOR] = true,
	[TEAM_MFOMED] = true,
	[TEAM_MFODOG] = true,
	[TEAM_MFOW] = true,
	[TEAM_MFOWS] = true,
	[TEAM_MFOHDGEN] = true,
}

-- Hitman team
DarkRP.addHitmanTeam(TEAM_KLASADZB)

-- Demote groups
DarkRP.createDemoteGroup("Cops", {TEAM_POLICE, TEAM_CHIEF})
DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})

-- Default categories
DarkRP.createCategory{
    name = "Citizens",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}

DarkRP.createCategory{
    name = "Civil Protection",
    categorises = "jobs",
    startExpanded = true,
    color = Color(25, 25, 170, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}

DarkRP.createCategory{
    name = "Gangsters",
    categorises = "jobs",
    startExpanded = true,
    color = Color(75, 75, 75, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}

DarkRP.createCategory{
    name = "Admin of duty",
    categorises = "jobs",
    startExpanded = true,
    color = Color(255, 13, 0),
    canSee = fp{fn.Id, true},
    sortOrder = 1,
}

DarkRP.createCategory{
    name = "Zarząd",
    categorises = "jobs",
    startExpanded = true,
    color = Color(101, 102, 102),
    canSee = fp{fn.Id, true},
    sortOrder = 3,
}

DarkRP.createCategory{
    name = "FO - Ochrona",
    categorises = "jobs",
    startExpanded = true,
    color = Color(3, 87, 150),
    canSee = fp{fn.Id, true},
    sortOrder = 4,
}

DarkRP.createCategory{
    name = "FT Siły Reagowania",
    categorises = "jobs",
    startExpanded = true,
    color = Color(10, 0, 204),
    canSee = fp{fn.Id, true},
    sortOrder = 5,
}

DarkRP.createCategory{
    name = "MFO - Alpha 1",
    categorises = "jobs",
    startExpanded = true,
    color = Color(10, 0, 204),
    canSee = fp{fn.Id, true},
    sortOrder = 5,
}

DarkRP.createCategory{
    name = "MFO - Hammer Down",
    categorises = "jobs",
    startExpanded = true,
    color = Color(10, 0, 204),
    canSee = fp{fn.Id, true},
    sortOrder = 6,
}

DarkRP.createCategory{
    name = "Klasy",
    categorises = "jobs",
    startExpanded = true,
    color = Color(212, 125, 4),
    canSee = fp{fn.Id, true},
    sortOrder = 2,
}

DarkRP.createCategory{
    name = "SCP",
    categorises = "jobs",
    startExpanded = true,
    color = Color(153, 119, 6),
    canSee = fp{fn.Id, true},
    sortOrder = 10,
}

DarkRP.createCategory{
    name = "Rebelia Chaosu",
    categorises = "jobs",
    startExpanded = true,
    color = Color(6, 153, 82),
    canSee = fp{fn.Id, true},
    sortOrder = 9,
}

DarkRP.createCategory{
    name = "Departament",
    categorises = "jobs",
    startExpanded = true,
    color = Color(161, 32, 124),
    canSee = fp{fn.Id, true},
    sortOrder = 7,
}

DarkRP.createCategory{
    name = "Naukowcy",
    categorises = "jobs",
    startExpanded = true,
    color = Color(50, 122, 173),
    canSee = fp{fn.Id, true},
    sortOrder = 8,
}

DarkRP.createCategory{
    name = "Eventowe",
    categorises = "jobs",
    startExpanded = true,
    color = Color(50, 122, 173),
    canSee = fp{fn.Id, true},
    sortOrder = 11,
}

DarkRP.createCategory{
    name = "Other",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}
