--[[---------------------------------------------------------------------------
DarkRP custom jobs
---------------------------------------------------------------------------
This file contains your custom jobs.
This file should also contain jobs from DarkRP that you edited.

Note: If you want to edit a default DarkRP job, first disable it in darkrp_config/disabled_defaults.lua
      Once you've done that, copy and paste the job to this file and edit it.

The default jobs can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua

For examples and explanation please visit this wiki page:
https://darkrp.miraheze.org/wiki/DarkRP:CustomJobFields

Add your custom jobs under the following line:
---------------------------------------------------------------------------]]

-- Autorem tych prac jest: Zabójca997 SteamID: STEAM_0:0:96053498
-- © Prawa autorskie zastrzeżone.
-- Zakazuje usuwania linijki o autorze oraz uzycia do celów komercyjnych.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
---TEAM_CITIZEN = DarkRP.createJob("Citizen", {
  --  color = Color(255, 120, 0, 255),
  --  model = {
   --     "models/classd/player/prisoners/jumpsuitm01.mdl",
---"models/classd/player/prisoners/jumpsuitm02.mdl",
 --       "models/classd/player/prisoners/jumpsuitm03.mdl",
 --       "models/classd/player/prisoners/jumpsuitm04.mdl",
 --       "models/classd/player/prisoners/jumpsuitm05.mdl",
 --       "models/classd/player/prisoners/jumpsuitm06.mdl",
--		"models/classd/player/prisoners/jumpsuitm07.mdl",
 --   },
 ---   description = [[Klasa D jest to domyślna klasa która jest brana na Badania]],
--    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
--    command = "citizen",
--    max = 0,
 --   salary = GAMEMODE.Config.normalsalary,
 --   admin = 0,
 --   vote = false,
--    hasLicense = false,
 --   candemote = false,
  --  category = "Citizens",
--	customCheck = function(ply) return
 --       table.HasValue({"STEAM_0:0:96053498"}, ply:SteamID())
 --   end,
--})

TEAM_KLASAD = DarkRP.createJob("Klasa D", {
    color = Color(255, 120, 0, 255),
    model = {
        "models/classd/player/prisoners/jumpsuitm01.mdl",
        "models/classd/player/prisoners/jumpsuitm02.mdl",
        "models/classd/player/prisoners/jumpsuitm03.mdl",
        "models/classd/player/prisoners/jumpsuitm04.mdl",
        "models/classd/player/prisoners/jumpsuitm05.mdl",
        "models/classd/player/prisoners/jumpsuitm06.mdl",
		"models/classd/player/prisoners/jumpsuitm07.mdl",
		"models/scp_class_d/female/d_female_01.mdl",
		"models/scp_class_d/female/d_female_02.mdl",
		"models/scp_class_d/female/d_female_03.mdl",
		"models/scp_class_d/female/d_female_04.mdl",
		"models/scp_class_d/female/d_female_05.mdl",
		"models/scp_class_d/female/d_female_06.mdl",
		"models/scp_class_d/female/d_female_07.mdl",
		"models/scp_class_d/female/d_female_08.mdl",
		"models/scp_class_d/female/d_female_09.mdl",
		"models/scp_class_d/female/d_female_10.mdl",
    },
    description = [[Klasa D jest to domyślna klasa która jest brana na Badania]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "KlasaD",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Klasy",
})

TEAM_KLASADZB = DarkRP.createJob("Klasa D - (Płatny zabójca)", {
    color = Color(255, 120, 0, 255),
    model = {
        "models/classd/player/prisoners/jumpsuitm01.mdl",
        "models/classd/player/prisoners/jumpsuitm02.mdl",
        "models/classd/player/prisoners/jumpsuitm03.mdl",
        "models/classd/player/prisoners/jumpsuitm04.mdl",
        "models/classd/player/prisoners/jumpsuitm05.mdl",
        "models/classd/player/prisoners/jumpsuitm06.mdl",
		"models/classd/player/prisoners/jumpsuitm07.mdl",
		"models/scp_class_d/female/d_female_01.mdl",
		"models/scp_class_d/female/d_female_02.mdl",
		"models/scp_class_d/female/d_female_03.mdl",
		"models/scp_class_d/female/d_female_04.mdl",
		"models/scp_class_d/female/d_female_05.mdl",
		"models/scp_class_d/female/d_female_06.mdl",
		"models/scp_class_d/female/d_female_07.mdl",
		"models/scp_class_d/female/d_female_08.mdl",
		"models/scp_class_d/female/d_female_09.mdl",
		"models/scp_class_d/female/d_female_10.mdl",
    },
    description = [[Klasa D jest to domyślna klasa z możliwością przyjęcia zabójstwa wybranego celu]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "Klasaplatna",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 2,
    category = "Klasy",
})

TEAM_KLASAS = DarkRP.createJob("Sprzątacz", {
    color = Color(255, 120, 0, 255),
    model = {
        "models/player/kerry/class_jan_2.mdl",
        "models/player/kerry/class_jan_3.mdl",
        "models/player/kerry/class_jan_4.mdl",
        "models/player/kerry/class_jan_5.mdl",
        "models/player/kerry/class_jan_6.mdl",
        "models/player/kerry/class_jan_7.mdl",
    },
    description = [[Sprzątacze to klasa D uprawniona do czyszczenia fundacji za bycie grzecznym oraz podporządkowanym]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_pass_rp", "guthscp_keycard_lvl_1", "surrender_animation_swep"},
    command = "Sprzatacz",
    max = 3,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 3,
    category = "Klasy",
})

TEAM_KWATER = DarkRP.createJob("Kwatermistrz", {
    color = Color(153, 79, 0, 255),
    model = {
        "models/player/monk.mdl",
    },
    description = [[Kwatermistrz to osoba uzupełniająca amunicje w fundacji]],
    weapons = {"weapon_fists", "weapon_empty_hands", "guthscp_keycard_lvl_1", "weapon_pass_rp", "surrender_animation_swep"},
    command = "Kwatermistrz",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	hobo = true,
	level = 4,
    category = "Klasy",
})

TEAM_KUCHARZ = DarkRP.createJob("Kucharz", {
    color = Color(153, 79, 0, 255),
    model = {
        "models/player/p_butcher.mdl",
    },
    description = [[Kucharz to personel placówki uprawniona do gotowania klasie D.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "guthscp_keycard_lvl_1", "csgo_stiletto", "weapon_pass_rp", "surrender_animation_swep"},
    command = "Kucharz",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	hobo = true,
	level = 5,
    category = "Klasy",
})

---TEAM_POLICE = DarkRP.createJob("Civil Protection", {
  --  color = Color(25, 25, 170, 255),
  --  model = {"models/player/police.mdl", "models/player/police_fem.mdl"},
---description = [[.]],
  ---  weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
  --  command = "cp",
  --  max = 4,
  --  salary = GAMEMODE.Config.normalsalary * 1.45,
  ---  admin = 0,
 --   vote = true,
  --  hasLicense = true,
 --   ammo = {
----["pistol"] = 60,
    ---},
  --  category = "Civil Protection",
--	customCheck = function(ply) return
 --       table.HasValue({"STEAM_0:0:96053498"}, ply:SteamID())
   -- end,
---})

--TEAM_GANG = DarkRP.createJob("Gangster", {
--    color = Color(75, 75, 75, 255),
--    model = {
--        "models/player/Group03/Female_01.mdl",
--	},
--    description = [[]],
--    weapons = {},
--    command = "gangster",
--    max = 3,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    category = "Gangsters",
--})

---TEAM_MOB = DarkRP.createJob("Mob boss", {
 --   color = Color(25, 25, 25, 255),
 --   model = "models/player/gman_high.mdl",
 --   description = [[The Mob boss is the boss of the criminals in the city.
 --       With his power he coordinates the gangsters and forms an efficient crime organization.
  ---      He has the ability to break into houses by using a lockpick.
  --      The Mob boss posesses the ability to unarrest you.]],
  ---  weapons = {"lockpick", "unarrest_stick"},
 --   command = "mobboss",
 --   max = 1,
 --   salary = GAMEMODE.Config.normalsalary * 1.34,
 --   admin = 0,
  --  vote = false,
  --  hasLicense = false,
  --  category = "Gangsters",
	--customCheck = function(ply) return
  --      table.HasValue({}, ply:SteamID())
  --  end,
--})

--TEAM_GUN = DarkRP.createJob("Gun Dealer", {
--    color = Color(255, 140, 0, 255),
--    model = "models/player/monk.mdl",
--    description = [[A Gun Dealer is the only person who can sell guns to other people.
--        Make sure you aren't caught selling illegal firearms to the public! You might get arrested!]],
--    weapons = {},
--    command = "gundealer",
--    max = 2,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    category = "Citizens",
--})

--TEAM_MEDIC = DarkRP.createJob("Medic", {
--    color = Color(47, 79, 79, 255),
--    model = "models/player/kleiner.mdl",
--    description = [[With your medical knowledge you work to restore players to full health.
--        Without a medic, people cannot be healed.
--        Left click with the Medical Kit to heal other players.
--        Right click with the Medical Kit to heal yourself.]],
--    weapons = {"med_kit"},
--    command = "medic",
--    max = 3,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    medic = true,
--    category = "Citizens",
--})

--TEAM_CHIEF = DarkRP.createJob("Civil Protection Chief", {
--    color = Color(20, 20, 255, 255),
--    model = "models/player/combine_soldier_prisonguard.mdl",
--    description = [[The Chief is the leader of the Civil Protection unit.
--        Coordinate the police force to enforce law in the city.
--        Hit a player with arrest baton to put them in jail.
--        Bash a player with a stunstick and they may learn to obey the law.
--        The Battering Ram can break down the door of a criminal, with a warrant for his/her arrest.
--        Type /wanted <name> to alert the public to the presence of a criminal.
--        Type /jailpos to set the Jail Position]],
--    weapons = {"arrest_stick", "unarrest_stick", "weapon_deagle2", "stunstick", "door_ram", "weaponchecker"},
--    command = "chief",
--    max = 1,
--    salary = GAMEMODE.Config.normalsalary * 1.67,
--    admin = 0,
--    vote = false,
--    hasLicense = true,
--    chief = true,
--    NeedToChangeFrom = TEAM_POLICE,
--    ammo = {
--        ["pistol"] = 60,
--    },
--    category = "Civil Protection",
--})

--TEAM_MAYOR = DarkRP.createJob("Mayor", {
--    color = Color(150, 20, 20, 255),
--    model = "models/player/breen.mdl",
--    description = [[The Mayor of the city creates laws to govern the city.
--    If you are the mayor you may create and accept warrants.
--    Type /wanted <name>  to warrant a player.
--    Type /jailpos to set the Jail Position.
--    Type /lockdown initiate a lockdown of the city.
--    Everyone must be inside during a lockdown.
--    The cops patrol the area.
--    /unlockdown to end a lockdown]],
--    weapons = {},
--    command = "mayor",
--    max = 1,
--    salary = GAMEMODE.Config.normalsalary * 1.89,
--    admin = 0,
--    vote = true,
--    hasLicense = false,
--    mayor = true,
--    category = "Civil Protection",
--})

--TEAM_HOBO = DarkRP.createJob("Hobo", {
--    color = Color(80, 45, 0, 255),
--    model = "models/player/corpse1.mdl",
--    description = [[The lowest member of society. Everybody laughs at you.
--        You have no home.
--        Beg for your food and money
--        Sing for everyone who passes to get money
--        Make your own wooden home somewhere in a corner or outside someone else's door]],
--    weapons = {"weapon_bugbait"},
--    command = "hobo",
--    max = 5,
--    salary = 0,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    candemote = false,
--    hobo = true,
--    category = "Citizens",
--}) 

TEAM_ADMIN = DarkRP.createJob("Administracja", {
    color = Color(255, 0, 0, 250),
	model = {
        "models/kss/tsremastered/smod_tactical_soldier.mdl",
    },
    description = [[Jest to Administracja serwer obecna do pomocy inaczej AdminOnDuty]],
    weapons = {"arrest_stick", "door_ram", "weapon_966", "stunstick", "pocketchecker", "hidden_knife", "weapon_camo", "weapon_beam", "card_lvl_5", "gmod_tool"},
    command = "Admini",
    max = 5,
    salary = 1000,
    admin = 1,
    vote = false,
    hasLicense = true,
    candemote = true,
	mayor = true,
    category = "Admin of duty",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100000)
        ply:SetHealth(100000)
        ply:SetArmor(1000)
    end
})
-- SCP
TEAM_SCP173 = DarkRP.createJob("SCP 173", {
    color = Color(150, 63, 0),
    model = "models/jqueary/scp/unity/scp173/scp173unity.mdl",
    description = [[SCP-173 jest zbudowany z betonu i prętów zbrojeniowych oraz pomalowany farbą. SCP-173 jest żywy i ekstremalnie niebezpieczny. Obiekt nie może się poruszać, kiedy ktokolwiek na niego patrzy. Z obiektem należy zawsze utrzymywać kontakt wzrokowy.]],
    weapons = {"gu_scp_173"},
    command = "SCP-173",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 10,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(0)
    end
})

TEAM_SCP106 = DarkRP.createJob("SCP 106 [WL]", {
    color = Color(150, 63, 0),
    model = "models/scp/106/unity/unity_scp_106_player.mdl",
    description = [[SCP-106 to osobnik potrafiący przenieść cie do świata łzowego, może on przechodzić przez drzwi]],
    weapons = {"gu_scp_106"},
    command = "SCP-106",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 15,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(0)
    end
})

TEAM_SCP4000 = DarkRP.createJob("SCP 4000", {
    color = Color(150, 63, 0),
    model = "models/player/stenli/lycan_werewolf.mdl",
    description = [[SCP 4000 Usunieto]],
    weapons = {"eoti_werewolf_swep"},
    command = "SCP-4000",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 15,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCPREV = DarkRP.createJob("SCP Raven", {
    color = Color(150, 63, 0),
    model = "models/player/ravenwarriorplayer.mdl",
    description = [[SCP-Raven to osoba wyglądająca na ptaka lub wilka]],
    weapons = {"eoti_raven_swep"},
    command = "SCP-reven",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 15,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP008 = DarkRP.createJob("SCP 008", {
    color = Color(150, 63, 0),
    model = "models/player/undead/undead.mdl",
    description = [[SCP-008 Wirus Zombie]],
    weapons = {"eoti_zombie_swep"},
    command = "SCP-008",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 15,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP8602 = DarkRP.createJob("SCP 860-2", {
    color = Color(150, 63, 0),
    model = "models/props/forest_monster/forest_monster2.mdl",
    description = [[SCP-860-2 to jaszczur z drzwi]],
    weapons = {"weapon_scp8602"},
    command = "SCP-8602",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 13,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP096 = DarkRP.createJob("SCP 096 [WL]", {
    color = Color(150, 63, 0),
    model = "models/scp096anim/player/scp096pm_raf.mdl",
    description = [[SCP-096 Nieśmiałek nie wolno sie na niego patrzeć gdyż powoduje to u niego stan w którym bedzie musiał cie zabić!]],
    weapons = {"weapon_scp096swep"},
    command = "SCP-096",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 11,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(10000)
        ply:SetHealth(10000)
        ply:SetArmor(0)
    end
})

TEAM_SCP999 = DarkRP.createJob("SCP 999", {
    color = Color(150, 63, 0),
    model = "models/scp/999/jq/scp_999_pmjq.mdl",
    description = [[SCP-999 Jest to glut którego zdolności mogą wyleczyć cie z depresji lub uleczyć cie]],
    weapons = {"med_kit", "cscp_999"},
    command = "SCP-999",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 5,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(3000)
        ply:SetHealth(3000)
        ply:SetArmor(0)
    end
})

TEAM_SCP066 = DarkRP.createJob("SCP 066", {
    color = Color(150, 63, 0),
    model = "models/player/mrsilver/scp_066pm/scp_066_pm.mdl",
    description = [[SCP-066 To zabawka ericka która gdy nie potwierdzisz że jesteś erickiem może wydać z siebie mocny dzwięk zabijając cie]],
    weapons = {"weapon_scp066"},
    command = "SCP-066",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 7,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(3000)
        ply:SetHealth(3000)
        ply:SetArmor(0)
    end
})

TEAM_SCP131 = DarkRP.createJob("SCP 131", {
    color = Color(150, 63, 0),
    model = "models/thenextscp/scp131/scp131.mdl",
    description = [[SCP-131 Oczki strączne]],
    weapons = {"weapon_empty_hands"},
    command = "scp-131",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 6,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(2000)
        ply:SetHealth(2000)
        ply:SetArmor(0)
    end
})

TEAM_SCP939 = DarkRP.createJob("SCP 939", {
    color = Color(150, 63, 0),
	model = {
        "models/scp/939/unity/unity_scp_939.mdl",
    },
	model = "models/scp/939/unity/unity_scp_939.mdl",
    description = [[SCP-939 Jaszczur! nie widzi lecz bardzo dobrze słyszy a przy tym wypuszcza gaz amnezyjny]],
    weapons = {"weapon_scp939swep"},
    command = "SCP-939",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 10,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(8000)
        ply:SetHealth(8000)
        ply:SetArmor(0)
    end
})

TEAM_SCP1048A = DarkRP.createJob("SCP 1048-A", {
    color = Color(150, 63, 0),
	model = "models/1048/tdy/tdybrownpm.mdl",
    description = [[SCP-1048 Miś budowlany]],
    weapons = {"weapon_empty_hands"},
    command = "SCP-1048A",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 3,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(2000)
        ply:SetHealth(2000)
        ply:SetArmor(0)
    end
})

TEAM_SCP1048B = DarkRP.createJob("SCP 1048-B", {
    color = Color(150, 63, 0),
	model = "models/1048/tdyear/tdybrownearpm.mdl",
    description = [[SCP-1048 Miś z uszu morderczy]],
    weapons = {"scprp_weapon_scp_1048a"},
    command = "SCP-1048B",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 8,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP682 = DarkRP.createJob("SCP 682 [WL]", {
    color = Color(150, 63, 0),
    model = "models/veeds/scp/682.mdl",
    description = [[SCP-682 Nie nawidzi życia! zabija wszystko co sie rusza]],
    weapons = {"fv_scp682"},
    command = "SCP-682",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 20,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(50000)
        ply:SetHealth(50000)
        ply:SetArmor(0)
    end
})

TEAM_SCP049 = DarkRP.createJob("SCP 049", {
    color = Color(150, 63, 0),
    model = "models/vinrax/player/scp049_player.mdl",
    description = [[SCP-049 Plaga! Zabija dotykiem zamieniając cie w zombie]],
    weapons = {"scp_049_scp"},
    command = "SCP-049",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 10,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(100)
    end
})

TEAM_SCP966 = DarkRP.createJob("SCP 966", {
    color = Color(150, 63, 0),
    model = "models/vasey105/scp/scp966/scp-966.mdl",
    description = [[SCP-966 Niewidzialny! widzisz go tylko w NVG może cie próbować uspać]],
    weapons = {"weapon_966"},
    command = "SCP-966",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 8,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP457 = DarkRP.createJob("SCP 457 [VIP]", {
    color = Color(150, 63, 0),
    model = "models/player/undead/undead.mdl",
    description = [[SCP-457 jest to palący sie humanoid]],
    weapons = {"weapon_scp457"},
    command = "SCP-457",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 9,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP076 = DarkRP.createJob("SCP 076 [VIP]", {
    color = Color(150, 63, 0),
    model = "models/abel/abel.mdl",
    description = [[SCP-076 Abel jest humanoidem]],
    weapons = {"weapon_katana"},
    command = "SCP-076",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 7,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(8000)
        ply:SetHealth(8000)
        ply:SetArmor(0)
    end
})

TEAM_SCP343 = DarkRP.createJob("SCP 343 [VIP]", {
    color = Color(150, 63, 0),
    model = "models/player/gow3_zeus.mdl",
    description = [[SCP-343 Zwany bogiem]],
    weapons = {"weapon_fists", "weapon_empty_hands", "weapon_medkit"},
    command = "SCP-343",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 13,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(5000)
        ply:SetHealth(5000)
        ply:SetArmor(0)
    end
})

TEAM_SCP035 = DarkRP.createJob("SCP 035", {
    color = Color(150, 63, 0),
    model = "models/logone/player/035_player.mdl",
    description = [[SCP-035 Zwany Maską]],
    weapons = {"weapon_035"},
    command = "SCP-035",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
	level = 13,
    category = "SCP",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(3000)
        ply:SetHealth(3000)
        ply:SetArmor(0)
    end
})

-- MFO Epsilon 11
TEAM_MFOE1G = DarkRP.createJob("Generał MFO-Epsilon 11 [WL]", {
    color = Color(0, 37, 250),
    model = {
        "models/mtf/mtf remasteredhd.mdl",
    },
    description = [[Jest to Generał MFO Epsilon 11]],
    weapons = {"cw_blackops3_dlc2_isr27", "sg_adrenaline", "cw_blackops3_mr6", "cw_blackops3_melee_combat", "cw_flash_grenade", "weapon_empty_hands", "keys", "weapon_pass_rp", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "weapon_camo", "dradio", "weapon_ai_noisemaker"},
    command = "MFO-E1G",
    max = 1,
    salary = 120,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	chief = true,
    category = "MFO - Epsilon 11",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(200)
    end
})

TEAM_MFOE1 = DarkRP.createJob("MFO-Epsilon 11 [WL]", {
    color = Color(0, 37, 250),
    model = {
        "models/ninja/mw3/delta/delta4_masked.mdl",
    },
    description = [[Jest to MFO Epsilon 11 
	Ma Za Zadanie Przyprowadzić Porządek w Placówce w Czasie Wyłomu lub Atatku na Placówke]],
    weapons = {"cw_p99", "sg_adrenaline", "cw_ar15", "cw_blackops3_melee_combat", "cw_flash_grenade", "weapon_empty_hands", "keys", "weapon_pass_rp", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "weapon_camo", "dradio", "weapon_ai_noisemaker"},
    command = "MFO-E1",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Epsilon 11",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(200)
    end
})

-- CI
TEAM_CIR = DarkRP.createJob("[EVENTOWY] Zołnierz CI [WL]", {
    color = Color(1, 148, 58),
    model = "models/friskiukas/bf4/ru_01.mdl",
    description = [[Żołnierz Rebeli Chaosu]],
    weapons = {"cw_ak74", "sg_adrenaline", "cw_smoke_grenade", "cw_flash_grenade", "cw_m1911", "csgo_bayonet_rustcoat", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "weapon_hdevice"},
    command = "CI-Rekrut",
    max = 4,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Rebelia Chaosu",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_CIS = DarkRP.createJob("[EVENTOWY] Zwiadowca CI [WL]", {
    color = Color(1, 148, 58),
    model = {
        "models/player/pmc_4/pmc__02.mdl",
        "models/player/pmc_4/pmc__03.mdl",
        "models/player/pmc_4/pmc__04.mdl",
        "models/player/pmc_4/pmc__05.mdl",
        "models/player/pmc_4/pmc__06.mdl",
        "models/player/pmc_4/pmc__07.mdl",
        "models/player/pmc_4/pmc__08.mdl",
		"models/player/pmc_4/pmc__09.mdl",
		"models/player/pmc_4/pmc__10.mdl",
		"models/player/pmc_4/pmc__11.mdl",
		"models/player/pmc_4/pmc__12.mdl",
		"models/player/pmc_4/pmc__13.mdl",
		"models/player/pmc_4/pmc__14.mdl",
    },
    description = [[Zwiadowca rebeli chaosu ma za zadanie obserwowac fundacje]],
    weapons = {"cw_l85a2", "sg_adrenaline", "cw_smoke_grenade", "cw_flash_grenade", "cw_m1911", "csgo_bayonet_rustcoat", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "weapon_hdevice"},
    command = "CI-Szeregowy",
    max = 2,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Rebelia Chaosu",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(0)
    end
})

TEAM_CIG = DarkRP.createJob("[EVENTOWY] Generał CI [WL]", {
    color = Color(1, 148, 58),
    model = "models/player/pmc_1/pmc__01.mdl",
    description = [[Generał rebeli chaosu]],
    weapons = {"cw_m249_official", "sg_adrenaline", "cw_smoke_grenade", "cw_flash_grenade", "cw_m1911", "csgo_butterfly_crimsonwebs", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "weapon_hdevice", "dradio"},
    command = "CI-Generał",
    max = 1,
    salary = 60,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Rebelia Chaosu",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})
-- Zarząd
TEAM_DEPZARZ = DarkRP.createJob("Rada O5 [Admin Only]", {
    color = Color(66, 66, 66),
    model = {
        "models/player/nick/scp/head_of_security/hos.mdl",
		"models/player/nick/scp/site_director/sd.mdl",
		"models/player/suits/male_09_open_waistcoat.mdl",
		"models/player/suits/male_09_open_tie.mdl",
		"models/player/suits/male_09_open.mdl",
		"models/player/suits/male_09_closed_tie.mdl",
		"models/player/suits/male_09_closed_coat_tie.mdl",
		"models/player/suits/male_08_shirt_tie.mdl",
		"models/player/suits/male_08_shirt.mdl",
		"models/player/suits/male_08_open_waistcoat.mdl",
		"models/player/suits/male_08_open_tie.mdl",
		"models/player/suits/male_08_open.mdl",
		"models/player/suits/male_08_closed_tie.mdl",
		"models/player/suits/male_08_closed_coat_tie.mdl",
		"models/player/suits/male_07_shirt_tie.mdl",
		"models/player/suits/male_07_shirt.mdl",
		"models/player/suits/male_07_open_waistcoat.mdl",
		"models/player/suits/male_07_open_tie.mdl",
		"models/player/suits/male_07_open.mdl",
		"models/player/suits/male_07_closed_tie.mdl",
		"models/player/suits/male_07_closed_coat_tie.mdl",
		"models/player/suits/male_06_shirt_tie.mdl",
		"models/player/suits/male_06_shirt.mdl",
		"models/player/suits/male_06_open_waistcoat.mdl",
		"models/player/suits/male_06_open_tie.mdl",
		"models/player/suits/male_06_open.mdl",
		"models/player/suits/male_06_closed_tie.mdl",
		"models/player/suits/male_06_closed_coat_tie.mdl",
		"models/player/suits/male_05_shirt_tie.mdl",
		"models/player/suits/male_05_open_waistcoat.mdl",
		"models/player/suits/male_05_open_tie.mdl",
		"models/player/suits/male_05_open.mdl",
		"models/player/suits/male_05_closed_tie.mdl",
		"models/player/suits/male_04_shirt_tie.mdl",
		"models/player/suits/male_04_shirt.mdl",
		"models/player/suits/male_04_open_waistcoat.mdl",
		"models/player/suits/male_04_open_tie.mdl",
		"models/player/suits/male_04_open.mdl",
		"models/player/suits/male_04_closed_tie.mdl",
		"models/player/suits/male_04_closed_coat_tie.mdl",
		"models/player/suits/male_03_shirt_tie.mdl",
		"models/player/suits/male_03_shirt.mdl",
		"models/player/suits/male_03_open_waistcoat.mdl",
		"models/player/suits/male_03_open_tie.mdl",
		"models/player/suits/male_03_open.mdl",
		"models/player/suits/male_03_closed_tie.mdl",
	},
    description = [[Dowództwo O5. Jest tajny i zwracać można sie do nich wyższy komitecie ds. etyki]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_p99", "door_ram", "stunstick", "sg_medkit", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "guthscp_keycard_omni", "dradio"},
    command = "radao5",
    max = 5,
    salary = 300,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Zarząd",
    mayor = true,
    chief = true,
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(150)
        ply:SetHealth(150)
        ply:SetArmor(150)
    end
})

TEAM_DEPDYR = DarkRP.createJob("Dyrektor Placówki [WL]", {
    color = Color(66, 66, 66),
    model = {
        "models/player/nick/scp/head_of_security/hos.mdl",
		"models/player/nick/scp/site_director/sd.mdl",
		"models/player/suits/male_05_open_tie.mdl",
		"models/player/suits/male_05_open.mdl",
		"models/player/suits/male_05_closed_tie.mdl",
	},
    description = [[Dyrektorzy istotnych placówek Fundacji to najważniejsi ich pracownicy odpowiedzialni za wszystko.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_mr96", "stunstick", "door_ram", "sg_medkit", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "guthscp_keycard_lvl_5", "dradio"},
    command = "Dyrektorp",
    max = 1,
    salary = 290,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Zarząd",
    mayor = true,
    chief = true,
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(120)
        ply:SetHealth(120)
        ply:SetArmor(100)
    end
})
-- VIP
TEAM_DEPDS = DarkRP.createJob("Specjalista ds. przechowywania [VIP]", {
    color = Color(110, 110, 110),
    model = "models/player/r6s_kapkan.mdl",
    description = [[Pełnisz role w zespołach zabezpieczających do potwierdzonych anomalii, by je zabezpieczyć ]],
    weapons = {"weapon_fists", "weapon_empty_hands", "stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_3", "weapon_cuff_elastic"},
    command = "spedsp",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 9,
    category = "Zarząd",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(50)
    end
})

-- Departamenty
TEAM_DEPLOG = DarkRP.createJob("Logistyki", {
    color = Color(153, 2, 75),
    model = {
        "models/scp_special_scp/special_7.mdl",
    },
    description = [[DL odpowiedzialny jest za transfery zasobów naturalnych, finansowych oraz ludzkich pomiędzy placówkami.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_2"},
    command = "Dep-log",
    max = 2,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 1,
    category = "Departament",
})

TEAM_DEPMED = DarkRP.createJob("Medycyny", {
    color = Color(153, 2, 75),
    model = {
        "models/player/kerry/medic/medic_01.mdl",
        "models/player/kerry/medic/medic_01_f.mdl",
        "models/player/kerry/medic/medic_02.mdl",
        "models/player/kerry/medic/medic_02_f.mdl",
        "models/player/kerry/medic/medic_03.mdl",
        "models/player/kerry/medic/medic_03_f.mdl",
		"models/player/kerry/medic/medic_04.mdl",
		"models/player/kerry/medic/medic_04_f.mdl",
		"models/player/kerry/medic/medic_05.mdl",
		"models/player/kerry/medic/medic_05_f.mdl",
		"models/player/kerry/medic/medic_06.mdl",
		"models/player/kerry/medic/medic_06_f.mdl",
		"models/player/kerry/medic/medic_07.mdl",
		"models/redninja/pmedic01f.mdl",
		"models/player/kerry/medic/medic_01_f.mdl",
		"models/player/kerry/medic/medic_02_f.mdl",
		"models/player/kerry/medic/medic_06_f.mdl",
		"models/player/kerry/medic/medic_05_f.mdl",
		"models/player/kerry/medic/medic_04_f.mdl",
    },
    description = [[DM odpowiedzialny jest za utrzymywanie zdrowia pracowników SCP.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_2", "med_kit", "weapon_physgun", "weapon_physcannon"},
    command = "Dep-Med",
    max = 3,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 3,
    category = "Departament",
})

TEAM_DEPORD = DarkRP.createJob("Ordynator [WL]", {
    color = Color(153, 2, 75),
    model = {
        "models/scp/apsci_cohrt.mdl",
        "models/scp/apsci_male_02.mdl",
        "models/scp/apsci_male_03.mdl",
        "models/scp/apsci_male_07.mdl",
        "models/scp/apsci_male_08.mdl",
    },
    description = [[Ordynator kontroluje medyków aby poprawnie leczyli ludzi.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_3", "med_kit", "weapon_physgun", "weapon_physcannon"},
    command = "Dep-ord",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 3,
    category = "Departament",
})

-- Komitet
TEAM_DEPET = DarkRP.createJob("Komitet ds. Etyki [WL]", {
    color = Color(66, 0, 166),
    model = {
		"models/player/suits/male_03_shirt_tie.mdl",
		"models/player/suits/male_03_shirt.mdl",
		"models/player/suits/male_03_open_waistcoat.mdl",
		"models/player/suits/male_03_open_tie.mdl",
		"models/player/suits/male_03_open.mdl",
		"models/player/suits/male_03_closed_tie.mdl",
    },
    description = [[Możesz mówić że coś jest nie etyczne oraz przerywać i karać osoby które robią coś nie etycznego.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "stunstick", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_4", "med_kit", "weapon_cuff_elastic", "dradio"},
    command = "Dep-Etyk",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Zarząd",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(90)
    end
})

TEAM_DEPINZ = DarkRP.createJob("Inżynierii", {
    color = Color(153, 2, 75),
    model = "models/mass effect 2/player/player/loki_mech.mdl",
    description = [[DI odpowiedzialny jest za utrzymywanie sprzętu technicznego oraz wszelkich usług dostępnych w placówkach Fundacji ]],
    weapons = {"weapon_fists", "weapon_empty_hands", "sg_adrenaline", "weapon_pass_rp", "keys", "guthscp_keycard_lvl_2"},
    command = "Dep-Inz",
    max = 2,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 3,
    category = "Departament",
})

-------------------------------------------------------------------------------->------------------------------>----------------OCHRONA---------------------------------------------------------------------<-----------------------------------<---------------------
TEAM_SZEFOCH = DarkRP.createJob("Szef Ochrony [WL]", {
	color = Color(1, 84, 153, 255),
	model = {
        "models/player/suits/male_01_closed_coat_tie.mdl",
        "models/player/suits/male_01_closed_tie.mdl",
        "models/player/suits/male_01_open.mdl",
        "models/player/suits/male_01_open_tie.mdl",
        "models/player/suits/male_01_open_waistcoat.mdl",
        "models/player/suits/male_01_shirt_tie.mdl",
        "models/player/suits/male_01_shirt.mdl",
		"models/player/suits/male_02_closed_coat_tie.mdl",
		"models/player/suits/male_02_closed_tie.mdl",
    },
	description = [[Szef ochrony zarządza całą Formacja Ochrony w Placówce]],
	weapons = {"sg_adrenaline", "cw_p99", "guthscp_keycard_lvl_4", "weapon_empty_hands", "stunstick", "pocket", "salute_swep", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "cross_arms_infront_swep", "dradio"},
	command = "SzefOch",
	max = 1,
	salary = 90,
	admin = 0,
	vote = false,
	hasLicense = true,
	candemote = true,
	category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_AgentDB = DarkRP.createJob("Agent DB [WL]", {
	color = Color(1, 84, 153, 255),
	model = {
        "models/player/suits/male_01_closed_coat_tie.mdl",
        "models/player/suits/male_01_closed_tie.mdl",
        "models/player/suits/male_01_open.mdl",
        "models/player/suits/male_01_open_tie.mdl",
        "models/player/suits/male_01_open_waistcoat.mdl",
        "models/player/suits/male_01_shirt_tie.mdl",
        "models/player/suits/male_01_shirt.mdl",
		"models/player/suits/male_02_closed_coat_tie.mdl",
		"models/player/suits/male_02_closed_tie.mdl",
    },
	description = [[Departament bezpieczeństwa zarządza całym bezpieczeństwem w placówce]],
	weapons = {"sg_adrenaline", "cw_deagle", "guthscp_keycard_lvl_4", "weapon_empty_hands", "stunstick", "pocket", "salute_swep", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "cross_arms_swep", "cross_arms_infront_swep", "dradio"},
	command = "Agentdb",
	max = 1,
	salary = 120,
	admin = 0,
	vote = false,
	hasLicense = true,
	candemote = true,
	category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})


TEAM_OCHRONA = DarkRP.createJob("Starszy Ochorniarz", {
    color = Color(2, 90, 153),
    model = {
        "models/player/humans/class_scientist/class_securety/class_securety_2.mdl",
    },
    description = [[Starszy ochroniarz ma za zadanie pilnować niższy personel ochrony do pracy]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "cw_m1911", "cw_g36c", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_3", "salute_swep", "dradio", "stunstick"},
    command = "Ochrona-St",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 20,
    category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_OCHRONASA = DarkRP.createJob("Sanitariusz Ochrony", {
    color = Color(2, 90, 153),
    model = {
        "models/payday2/units/medic_player_pd2anim.mdl",
    },
    description = [[Sanitariusz ochrony zajmuje sie pilnowaniem Klasy D oraz badaniami na SCP lecz swoich kolegów z fo]],
    weapons = {"weapon_fists", "weapon_empty_hands", "csgo_m9_night", "stunstick", "cw_fiveseven", "cw_g36c", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_2", "salute_swep", "dradio", "med_kit"},
    command = "Ochrona-SA",
    max = 2,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 15,
    category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(80)
    end
})

TEAM_POCHRONA = DarkRP.createJob("Ochrona", {
    color = Color(2, 90, 153),
    model = {
        "models/player/humans/class_scientist/class_securety/class_securety.mdl",
		"models/cso2/player/ct_helga_player.mdl",
    },
    description = [[Ochrona zajmuje sie pilnowaniem Personelu Klasy D]],
    weapons = {"weapon_fists", "weapon_empty_hands", "stunstick", "cw_fiveseven", "cw_mp5", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_2", "salute_swep", "dradio"},
    command = "Ochrona",
    max = 5,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 10,
    category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(50)
    end
})

TEAM_BOTCHRONA = DarkRP.createJob("BOT [VIP]", {
    color = Color(2, 90, 153),
    model = {
        "models/vanquish/player/augmented_reaction_suit.mdl",
    },
    description = [[Bot pacyfikacyjny ochrony zajmuje sie Patrolowaniem Klasy D i poziomu bliskiego mu lub wyznaczonego]],
    weapons = {"weapon_fists", "weapon_empty_hands", "stunstick", "cw_fiveseven", "cw_blackops3_xr2", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_3", "dradio"},
    command = "Ochrona-bot",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "FO - Ochrona",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(150)
    end
})
------------------------------------------

-- MFO Ny-7 Hammer Down
TEAM_MFOHDZ = DarkRP.createJob("Ny-7 [WL]", {
    color = Color(0, 22, 150),
    model = {
        "models/scp_mtf_operator/mtf_operator.mdl",
    },
    description = [[Żołnierz MFO Hammer-Down jest batalionem składającym się z trzech wyspecjalizowanych pułków piechoty wielkości kompanii]],
    weapons = {"cw_ar15", "sg_adrenaline", "cw_p99", "csgo_m9_night", "cw_flash_grenade", "guthscp_keycard_lvl_3", "weapon_empty_hands", "weapon_pass_rp", "keys", "weapon_cuff_elastic", "dradio", "weapon_ai_noisemaker"},
    command = "MFO-Hammer-Down",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(130)
    end
})

TEAM_MFOHDGEN = DarkRP.createJob("General Ny-7 [WL]", {
    color = Color(0, 22, 150),
	model = {
        "models/npc/portal/male_08_garde.mdl",
    },
    description = [[Generał Mobilnej formacji operacyjnej]],
    weapons = {"cw_deagle", "sg_adrenaline", "cw_kk_hk416", "weapon_empty_hands", "weapon_pass_rp", "csgo_karambit_marblefade", "cw_flash_grenade", "keys", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "dradio", "weapon_ai_noisemaker"},
    command = "MFO-General",
    max = 1,
    salary = 120,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	chief = true,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(150)
    end
})

TEAM_MFOHDMED = DarkRP.createJob("Sanitariusz Ny-7 [WL]", {
    color = Color(0, 22, 150),
    model = {
        "models/scp/guard_med.mdl",
        "models/payday2/units/medic_player_pd2anim.mdl",
    },
    description = [[Sanitariusz Mobilnej formacji operacyjnej ma za zadanie leczyć swoich]],
    weapons = {"med_kit", "sg_adrenaline", "cw_ws_kabar", "cw_p99", "keys", "cw_flash_grenade", "weapon_empty_hands", "weapon_pass_rp", "weapon_cuff_elastic", "guthscp_keycard_lvl_3", "dradio", "weapon_ai_noisemaker"},
    command = "MFOHD-medyk",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 10,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_MFOHDDOG = DarkRP.createJob("Pies Ny-7 [WL]", {
    color = Color(0, 22, 150),
    model = "models/arachnit/wolfenstein2/kampfhund/kampfhund.mdl",
    description = [[Pies Mobilnej formacji operacyjnej ma za zadanie Pilnować porządku i wyszukiwać kontrabande]],
    weapons = {"weapon_pet", "weapon_empty_hands", "weapon_empty_hands"},
    command = "MFOHD-pies",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "MFO - Hammer Down",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

-- Formacja Taktyczna --
TEAM_FTS = DarkRP.createJob("FT - Żołnierz [WL]", {
    color = Color(0, 149, 255),
	model = {
        "models/player/PMC_4/PMC__02.mdl",
        "models/player/PMC_4/PMC__03.mdl",
        "models/player/PMC_4/PMC__04.mdl",
        "models/player/PMC_4/PMC__05.mdl",
        "models/player/PMC_4/PMC__06.mdl",
        "models/player/PMC_4/PMC__07.mdl",
        "models/player/PMC_4/PMC__08.mdl",
		"models/player/PMC_4/PMC__09.mdl",
		"models/player/PMC_4/PMC__10.mdl",
		"models/player/PMC_4/PMC__11.mdl",
		"models/player/PMC_4/PMC__12.mdl",
		"models/player/PMC_4/PMC__13.mdl",
		"models/player/PMC_4/PMC__14.mdl",
    },
    model = "models/player/PMC_4/PMC__02.mdl ",
    description = [[Zajmuj sie odparciem wroga oraz wyłamaniom SCP.]],
    weapons = {"cw_m14","cw_p99", "weapon_empty_hands", "weapon_cuff_elastic", "salute_swep", "stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_3", "dradio", "weapon_ai_noisemaker"},
    command = "FT-Żołnierz",
    max = 5,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "FT Siły Reagowania",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(90)
    end
})

TEAM_FTG = DarkRP.createJob("FT - Dowódca [WL]", {
    color = Color(0, 149, 255),
    model = "models/player/PMC_4/PMC__01.mdl",
    description = [[Szkoli FT i zajmuje sie odparciem wroga oraz wyłomami SCP.]],
    weapons = {"cw_m14", "cw_fiveseven", "weapon_cuff_elastic", "weapon_empty_hands", "salute_swep", "stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_4", "cross_arms_swep", "cross_arms_infront_swep", "dradio", "weapon_ai_noisemaker"},
    command = "FT-General",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "FT Siły Reagowania",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

--------------------------------------------------------------------------------------------------------------------------------------- MFO Alpha 1 ----------------------------------------------------------------------------------------------------------------------------------------------------------
TEAM_MFOA1GEN = DarkRP.createJob("Generał Alpha 1 [WL]", {
    color = Color(2, 90, 153),
    model = "models/kss/tsremastered/smod_operator_tac_01.mdl",
    description = [[Generał odpowiadający bezpośrednio przed Radą O5 oraz dyrektora placówki masz przy nich być i ich chronić oraz szkolić swój Odział MFO]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_g3a3", "stunstick", "salute_swep", "csgo_falchion_crimsonwebs", "dradio", "cw_p99", "cw_flash_grenade", "sg_adrenaline", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_4", "weapon_ai_noisemaker"},
    command = "MFOA1G",
    max = 1,
    salary = 120,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	chief = true,
    category = "MFO - Alpha 1",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_MFOA1 = DarkRP.createJob("Alpha 1 [WL]", {
    color = Color(2, 90, 153),
    model = {
        "models/scp_mtf_russian/mtf_rus_02.mdl",
        "models/scp_mtf_russian/mtf_rus_04.mdl",
        "models/scp_mtf_russian/mtf_rus_05.mdl",
		"models/scp_mtf_russian/mtf_rus_06.mdl",
		"models/scp_mtf_russian/mtf_rus_07.mdl",
		"models/scp_mtf_russian/mtf_rus_08.mdl",
    },
    description = [[Formacja odpowiadająca bezpośrednio przed Radą O5 oraz dyrektora placówki masz obowiązek ich chronić
	jak przy nich przebywać.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "cw_ar15", "salute_swep", "stunstick", "cw_p99", "csgo_falchion_bluesteel", "dradio", "cw_flash_grenade", "sg_adrenaline", "keys", "weapon_cuff_elastic", "weapon_pass_rp", "guthscp_keycard_lvl_4", "dradio", "weapon_ai_noisemaker"},
    command = "MFOA1",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 20,
    category = "MFO - Alpha 1",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

--------------------------------------------------------------------------------------------------------------------------------------- Naukowcy --------------------------------------------------------------------------------------------------------------------------------------------------------
TEAM_ASNaukowiec = DarkRP.createJob("Asystent Naukowy", {
    color = Color(0, 149, 255),
    model = {
        "models/player/humans/class_scientist/class_scientist_1.mdl",
		"models/scp_sci_new/female/s_female_01.mdl",
		"models/scp_sci_new/female/s_female_02.mdl",
		"models/scp_sci_new/female/s_female_03.mdl",
		"models/scp_sci_new/female/s_female_04.mdl",
		"models/scp_sci_new/female/s_female_05.mdl",
		"models/scp_sci_new/female/s_female_06.mdl",
		"models/scp_sci_new/female/s_female_07.mdl",
		"models/scp_sci_new/female/s_female_08.mdl",
		"models/scp_sci_new/female/s_female_09.mdl",
		"models/scp_sci_new/female/s_female_10.mdl",
		"models/scp_sci_new/sci_new_1.mdl",
		"models/scp_sci_new/sci_new_2.mdl",
		"models/scp_sci_new/sci_new_3.mdl",
		"models/scp_sci_new/sci_new_4.mdl",
		"models/scp_sci_new/sci_new_5.mdl",
		"models/scp_sci_new/sci_new_6.mdl",
		"models/scp_sci_new/sci_new_7.mdl",
		"models/scp_sci_new/sci_new_8.mdl",
		"models/scp_sci_new/sci_new_9.mdl",
    },
    description = [[Jako Asystent ucz sie badań i możesz przeprowadzać badania nad klasą Safe i składać raporty głównemu naukowcowi
	Pamietaj Zanim Będziesz Przeprowadzać Badania na Obiektach (SCP) Zgłoś Głownemu Naukowcowi!.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_1", "dradio"},
    command = "ASNaukowiec",
    max = 2,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 5,
    category = "Naukowcy",
})

TEAM_Naukowiec = DarkRP.createJob("Naukowiec [WL]", {
    color = Color(0, 149, 255),
    model = {
        "models/player/humans/class_scientist/class_scientist_2.mdl",
		"models/scp_sci_new/female/s_female_01.mdl",
		"models/scp_sci_new/female/s_female_02.mdl",
		"models/scp_sci_new/female/s_female_03.mdl",
		"models/scp_sci_new/female/s_female_04.mdl",
		"models/scp_sci_new/female/s_female_05.mdl",
		"models/scp_sci_new/female/s_female_06.mdl",
		"models/scp_sci_new/female/s_female_07.mdl",
		"models/scp_sci_new/female/s_female_08.mdl",
		"models/scp_sci_new/female/s_female_09.mdl",
		"models/scp_sci_new/female/s_female_10.mdl",
		"models/scp_sci_new/sci_new_1.mdl",
		"models/scp_sci_new/sci_new_2.mdl",
		"models/scp_sci_new/sci_new_3.mdl",
		"models/scp_sci_new/sci_new_4.mdl",
		"models/scp_sci_new/sci_new_5.mdl",
		"models/scp_sci_new/sci_new_6.mdl",
		"models/scp_sci_new/sci_new_7.mdl",
		"models/scp_sci_new/sci_new_8.mdl",
		"models/scp_sci_new/sci_new_9.mdl",
    },
    description = [[Jako naukowiec możesz przeprowadzać badania na Obiektach (SCP).
	Każde Raporty po przeporwadzonych testach na Obiektach SCP zgłoś do Naukowca Głownego!]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_3", "dradio"},
    command = "Naukowiec",
    max = 1,
    salary = 70,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	level = 8,
    category = "Naukowcy",
})

TEAM_STNaukowiec = DarkRP.createJob("Starszy Naukowiec [WL]", {
    color = Color(0, 149, 255),
    model = {
        "models/player/humans/class_scientist/class_scientist_5.mdl",
		"models/scp_sci_new/female/s_female_01.mdl",
		"models/scp_sci_new/female/s_female_02.mdl",
		"models/scp_sci_new/female/s_female_03.mdl",
		"models/scp_sci_new/female/s_female_04.mdl",
		"models/scp_sci_new/female/s_female_05.mdl",
		"models/scp_sci_new/female/s_female_06.mdl",
		"models/scp_sci_new/female/s_female_07.mdl",
		"models/scp_sci_new/female/s_female_08.mdl",
		"models/scp_sci_new/female/s_female_09.mdl",
		"models/scp_sci_new/female/s_female_10.mdl",
		"models/scp_sci_new/sci_new_1.mdl",
		"models/scp_sci_new/sci_new_2.mdl",
		"models/scp_sci_new/sci_new_3.mdl",
		"models/scp_sci_new/sci_new_4.mdl",
		"models/scp_sci_new/sci_new_5.mdl",
		"models/scp_sci_new/sci_new_6.mdl",
		"models/scp_sci_new/sci_new_7.mdl",
		"models/scp_sci_new/sci_new_8.mdl",
		"models/scp_sci_new/sci_new_9.mdl",
    },
    description = [[Jako Starszy naukowiec masz za zadanie Obserwowac Przebiegi Badań Jak i Samemu Przeprowadzać Badania na Obiektach (SCP)
	Po każdym zakończonym Przebiegu Badania / Obserwacji Zgłoś Raport do Naukowca Głównego.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_3", "stunstick", "dradio"},
    command = "ST-Naukowiec",
    max = 1,
    salary = 80,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	Level = 14,
    category = "Naukowcy",
})

TEAM_GłNaukowiec = DarkRP.createJob("Główny Naukowiec [WL]", {
    color = Color(0, 149, 255),
    model = "models/player/scientist.mdl",
    description = [[Jako główny naukowiec możesz zatwierdzać badania oraz szkolic swoich naukowców i przydzielać im tytuły.]],
    weapons = {"weapon_fists", "weapon_empty_hands", "salute_swep", "stunstick", "keys", "weapon_pass_rp", "guthscp_keycard_lvl_4", "dradio"},
    command = "Gł-Naukowiec",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Naukowcy",
})

-- Inne --
TEAM_CYW = DarkRP.createJob("Cywil [UCIECZKA]", {
    color = Color(0, 149, 255),
    model = {
        "models/player/female_02_suit.mdl",
        "models/humans/bms_worker_clean.mdl",
    },
    description = [[Cywil osoba która uciekła z placówki. i może żyć spokojnie]],
    weapons = {"weapon_empty_hands", "weapon_fists", "weapon_pass_rp", "keys"},
    command = "cywil",
    max = 10,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Eventowe",
})

-- PRYWATNE --
TEAM_JACK = DarkRP.createJob("Dr. Jack Bright", {
    color = Color(0, 149, 255),
    model = {
        "models/scp_special_scp/special_5.mdl",
    },
    description = [[Postać kanoniczna Dr. Jack Bright.]],
    weapons = {"weapon_empty_hands", "cw_deagle", "weapon_fists", "weapon_pass_rp", "sg_adrenaline", "guthscp_keycard_lvl_4", "dradio", "weapon_physcannon"},
    command = "jb",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Prywatne",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(120)
        ply:SetHealth(120)
        ply:SetArmor(150)
    end
})

TEAM_CLEF = DarkRP.createJob("Dr. Alton Clef", {
    color = Color(0, 149, 255),
    model = {
        "models/armacham/scientists/scientists_8.mdl",
    },
    description = [[Postać kanoniczna Dr. Altona Cleafa.]],
    weapons = {"weapon_empty_hands", "cw_blackops3_mr6", "weapon_fists", "weapon_pass_rp", "sg_adrenaline", "guthscp_keycard_lvl_4", "dradio", "weapon_physcannon"},
    command = "clef",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Prywatne",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_DRV = DarkRP.createJob("Dr. V", {
    color = Color(0, 149, 255),
    model = {
        "models/yates/rangercombatf.mdl",
    },
    description = [[Postać nie kanoniczna Dr. V.]],
    weapons = {"weapon_empty_hands", "cw_blackops3_mr6", "weapon_fists", "weapon_pass_rp", "sg_adrenaline", "guthscp_keycard_lvl_3", "dradio", "weapon_physcannon", "csgo_bowie_ultraviolet"},
    command = "drv",
    max = 1,
    salary = 90,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Prywatne",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(200)
        ply:SetHealth(200)
        ply:SetArmor(100)
    end
})

TEAM_DBWW = DarkRP.createJob("Agent WW [WL]", {
    color = Color(29, 59, 102, 255),
    model = {
		"models/player/assasinge/csuit.mdl",
        "models/player/suits/male_02_closed_coat_tie.mdl",
        "models/player/suits/male_04_closed_coat_tie.mdl",
        "models/player/suits/male_05_closed_coat_tie.mdl",
        "models/player/suits/male_06_closed_coat_tie.mdl",
        "models/player/suits/male_07_closed_coat_tie.mdl",
        "models/player/suits/male_08_closed_coat_tie.mdl",
        "models/player/suits/male_09_closed_coat_tie.mdl",
    },
    description = [[Agenci WW zajmuje się sprawami wewnątrz placówki. Prowadzą przesłuchania oraz śledztwa. Prowadzą także postępowania karne oraz przewodzą w odpowiednich sytuacjach ochroną.]],
    weapons = {"weapon_empty_hands", "stunstick", "lockpick", "weaponchecker", "dradio", "csgo_flip_lore", "weapon_cuff_elastic", "guthscp_keycard_lvl_4", "surrender_animation_swep", "salute_swep", "cross_arms_infront_swep", "cross_arms_swep", "cw_blackops3_38", "cw_m1911}"},
    command = "Zarząd",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	category = "Prywatne",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

TEAM_GRZEGORZ = DarkRP.createJob("Grzegorz", {
    color = Color(29, 59, 102, 255),
    model = {
        "models/player/kerry/class_jan_2.mdl",
        "models/player/kerry/class_jan_3.mdl",
        "models/player/kerry/class_jan_4.mdl",
        "models/player/kerry/class_jan_5.mdl",
        "models/player/kerry/class_jan_6.mdl",
        "models/player/kerry/class_jan_7.mdl",
    },
    description = [[Grzegorz sprzątacz o anomalnych zdolnościach (nad naturalna siła i wiedza o wszystkim). Pomógł nie raz z brechami, i zapobiegł ataku ci przez swoją wiedzę o wszystkim]],
    weapons = {"weapon_empty_hands", "stunstick", "lockpick", "csgo_flip_lore", "weapon_cuff_elastic", "guthscp_keycard_lvl_2", "surrender_animation_swep", "salute_swep", "cross_arms_infront_swep", "cross_arms_swep"},
    command = "grzego",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	category = "Prywatne",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(0)
    end
})

TEAM_KLAUD = DarkRP.createJob("Dyrektorka [WL]", {
    color = Color(29, 59, 102, 255),
    model = {
        "models/player/female_02_suit.mdl",
		"models/scp_special_scp/special_4.mdl",
		"models/cultist/scp/scp_1903.mdl",
		"models/cultist/scp/scp_029.mdl",
		"models/cultist/scp/scp_811.mdl",
    },
    description = [[Jest to anomalna dyrektora ośrodka 19, w gniewie może zmieniać swoją postać i stawać sie agresywan do osoby która ją zatakowała]],
    weapons = {"weapon_empty_hands", "dradio", "keys", "stunstick", "lockpick", "csgo_flip_lore", "weapon_cuff_elastic", "guthscp_keycard_lvl_5", "surrender_animation_swep", "salute_swep", "cross_arms_infront_swep", "cross_arms_swep", "cw_blackops3_38", "cw_m1911"},
    command = "dyrektorkaa",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
	category = "Zarząd",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(0)
    end
})

TEAM_DNDCB = DarkRP.createJob("Dr. Clara Birkin [PR]", {
    color = Color(15, 117, 111, 255),
    model = {
        "models/players/mj_re2_annette.mdl",
    },
    description = [[Dr. Clara Birkin jest to biochemikiem, narodziła się w 1989 na terenie Londynu. Ukończyła "Uniwersytet Oksfordzki" o kierunku bio-chemicznym, wygrała uniwersytecki konkurs chemicznym i ukończyła tą szkołę z wyróżnieniem. Po zakończonej nauce i osiągnięciu doktoratu w dziedzinie chemii, wyrobiła magistra medycyny.]],
    weapons = {"cw_fiveseven", "csgo_butterfly_bluesteel", "dradio", "guthscp_keycard_lvl_4", "weapon_pass_rp", "wep_jack_job_drpradio", "weapon_medkit"},
    command = "/DCBDN",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = false,
    category = "Naukowcy",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(50)
    end
})

if not DarkRP.disabledDefaults["modules"]["hungermod"] then
    TEAM_COOK = DarkRP.createJob("Cook", {
        color = Color(238, 99, 99, 255),
        model = "models/player/mossman.mdl",
        description = [[As a cook, it is your responsibility to feed the other members of your city.
            You can spawn a microwave and sell the food you make:
            /buymicrowave]],
        weapons = {},
        command = "cook",
        max = 2,
        salary = 45,
        admin = 0,
        vote = false,
        hasLicense = false,
        cook = true
    })
end

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Door groups
AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
AddDoorGroup("Gundealer only", TEAM_GUN)


-- Agendas
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})

-- Group chats
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_MFOA1GEN, TEAM_MFOA1)
DarkRP.createGroupChat(TEAM_MFOHDZW, TEAM_MFOR, TEAM_MFOMED, TEAM_MFODOG, TEAM_MFOW, TEAM_MFOWS, TEAM_MFOHDGEN)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_KLASAD

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,
	[TEAM_ADMIN] = true,
}

-- Hitman team
DarkRP.addHitmanTeam(TEAM_KLASADZB)

-- Demote groups
DarkRP.createDemoteGroup("Cops", {TEAM_POLICE, TEAM_CHIEF})
DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})

-- Default categories
--DarkRP.createCategory{
 --   name = "Citizens",
 --   categorises = "jobs",
  --  startExpanded = true,
  --  color = Color(0, 107, 0, 255),
  --  canSee = fp{fn.Id, true},
  --  sortOrder = 255,
--}

----DarkRP.createCategory{
  --  name = "Civil Protection",
  --  categorises = "jobs",
  --  startExpanded = true,
 --   color = Color(25, 25, 170, 255),
  --  canSee = fp{fn.Id, true},
 --   sortOrder = 255,
---}

---DarkRP.createCategory{
  --  name = "Gangsters",
 --   categorises = "jobs",
 --   startExpanded = true,
 --   color = Color(75, 75, 75, 255),
 --   canSee = fp{fn.Id, true},
  --  sortOrder = 255,
----}

DarkRP.createCategory{
    name = "Admin of duty",
    categorises = "jobs",
    startExpanded = true,
    color = Color(255, 13, 0),
    canSee = fp{fn.Id, true},
    sortOrder = 1,
}

DarkRP.createCategory{
    name = "Zarząd",
    categorises = "jobs",
    startExpanded = true,
    color = Color(101, 102, 102),
    canSee = fp{fn.Id, true},
    sortOrder = 3,
}

DarkRP.createCategory{
    name = "FO - Ochrona",
    categorises = "jobs",
    startExpanded = true,
    color = Color(3, 87, 150),
    canSee = fp{fn.Id, true},
    sortOrder = 4,
}

DarkRP.createCategory{
    name = "FT Siły Reagowania",
    categorises = "jobs",
    startExpanded = true,
    color = Color(10, 0, 204),
    canSee = fp{fn.Id, true},
    sortOrder = 5,
}

DarkRP.createCategory{
    name = "MFO - Alpha 1",
    categorises = "jobs",
    startExpanded = true,
    color = Color(10, 0, 204),
    canSee = fp{fn.Id, true},
    sortOrder = 5,
}

DarkRP.createCategory{
    name = "MFO - Hammer Down",
    categorises = "jobs",
    startExpanded = true,
    color = Color(10, 0, 204),
    canSee = fp{fn.Id, true},
    sortOrder = 6,
}

DarkRP.createCategory{
    name = "MFO - Epsilon 11",
    categorises = "jobs",
    startExpanded = true,
    color = Color(10, 0, 204),
    canSee = fp{fn.Id, true},
    sortOrder = 6,
}

DarkRP.createCategory{
    name = "Klasy",
    categorises = "jobs",
    startExpanded = true,
    color = Color(212, 125, 4),
    canSee = fp{fn.Id, true},
    sortOrder = 2,
}

DarkRP.createCategory{
    name = "SCP",
    categorises = "jobs",
    startExpanded = true,
    color = Color(153, 119, 6),
    canSee = fp{fn.Id, true},
    sortOrder = 10,
}

DarkRP.createCategory{
    name = "Rebelia Chaosu",
    categorises = "jobs",
    startExpanded = true,
    color = Color(6, 153, 82),
    canSee = fp{fn.Id, true},
    sortOrder = 9,
}

DarkRP.createCategory{
    name = "Departament",
    categorises = "jobs",
    startExpanded = true,
    color = Color(161, 32, 124),
    canSee = fp{fn.Id, true},
    sortOrder = 7,
}

DarkRP.createCategory{
    name = "Naukowcy",
    categorises = "jobs",
    startExpanded = true,
    color = Color(50, 122, 173),
    canSee = fp{fn.Id, true},
    sortOrder = 8,
}

DarkRP.createCategory{
    name = "Prywatne",
    categorises = "jobs",
    startExpanded = true,
    color = Color(50, 122, 173),
    canSee = fp{fn.Id, true},
    sortOrder = 9,
}

DarkRP.createCategory{
    name = "Eventowe",
    categorises = "jobs",
    startExpanded = true,
    color = Color(50, 122, 173),
    canSee = fp{fn.Id, true},
    sortOrder = 11,
}

DarkRP.createCategory{
    name = "Other",
    categorises = "jobs",
    startExpanded = false,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}
